// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

function readInput() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => {
      try { resolve(data.trim() ? JSON.parse(data) : {}); } catch { resolve({}); }
    });
  });
}

function findRoot(start) {
  let current = resolve(start);
  while (true) {
    if (existsSync(join(current, ".git")) || existsSync(join(current, ".mstack"))) return current;
    const parent = dirname(current);
    if (parent === current) return resolve(start);
    current = parent;
  }
}

function hasTests(root) {
  const candidates = ["test", "tests", "spec", "__tests__"];
  if (candidates.some((name) => existsSync(join(root, name)))) return true;
  const sourceRoots = ["src", "app", "apps", "packages"].map((name) => join(root, name));
  const queue = sourceRoots.filter(existsSync);
  let inspected = 0;
  while (queue.length && inspected < 500) {
    const path = queue.pop();
    inspected += 1;
    let entries = [];
    try { entries = readdirSync(path); } catch { continue; }
    for (const entry of entries) {
      const child = join(path, entry);
      let stats;
      try { stats = statSync(child); } catch { continue; }
      if (stats.isDirectory() && entry !== "node_modules" && entry !== "dist") queue.push(child);
      if (stats.isFile() && /(?:\.test|\.spec)\.[cm]?[jt]sx?$/.test(entry)) return true;
    }
  }
  return false;
}

const input = await readInput();
const root = findRoot(typeof input.cwd === "string" ? input.cwd : process.cwd());
const warnings = [];
const docs = join(root, "docs");
if (existsSync(docs)) {
  const markdown = readdirSync(docs).filter((name) => name.endsWith(".md"));
  if (markdown.length && !existsSync(join(docs, "product.md"))) warnings.push("docs/ exists but docs/product.md is missing");
  if (markdown.length && !existsSync(join(docs, "architecture.md"))) warnings.push("docs/ exists but docs/architecture.md is missing");
  for (const name of ["product.md", "architecture.md"]) {
    const path = join(docs, name);
    if (!existsSync(path)) continue;
    const content = readFileSync(path, "utf8");
    if (content.trim().length < 300) warnings.push("docs/" + name + " is too thin to guide material engineering decisions");
    if (/\{\{[^}]+\}\}/.test(content)) warnings.push("docs/" + name + " still contains unfilled template fields");
  }
}

const packagePath = join(root, "package.json");
if (existsSync(packagePath)) {
  try {
    const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
    const scripts = pkg.scripts || {};
    if (!scripts.test && hasTests(root)) warnings.push("tests exist but package.json has no test script");
    if (!scripts.build && (existsSync(join(root, "src")) || existsSync(join(root, "packages")))) warnings.push("source exists but package.json has no build script");
  } catch {
    warnings.push("package.json could not be parsed");
  }
}

if (warnings.length) {
  process.stderr.write("mstack repository health:\n" + warnings.slice(0, 5).map((item) => "- " + item).join("\n") + "\n");
}
process.stdout.write("{}\n");
