// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
async function readInput() {
  let data = "";
  process.stdin.setEncoding("utf8");
  for await (const chunk of process.stdin) {
    data += chunk;
    if (data.length > 1_000_000) return {};
  }
  try { return data.trim() ? JSON.parse(data) : {}; } catch { return {}; }
}

function findCommand(value, depth = 0) {
  if (depth > 5 || value == null || typeof value === "string") return "";
  if (Array.isArray(value)) {
    for (const item of value) { const found = findCommand(item, depth + 1); if (found) return found; }
    return "";
  }
  if (typeof value === "object") {
    if (typeof value.command === "string") return value.command;
    for (const item of Object.values(value)) { const found = findCommand(item, depth + 1); if (found) return found; }
  }
  return "";
}

const input = await readInput();
const command = findCommand(input);
const warnings = [];
const destructive = [
  /\brm\s+(?:-[^\s;&|]*[rR][^\s;&|]*[fF]|-[^\s;&|]*[fF][^\s;&|]*[rR]|--recursive\b[^;&|]*--force\b|--force\b[^;&|]*--recursive\b)/,
  /\bgit\s+reset\s+--hard\b/i,
  /\bgit\s+clean\s+-[^\s;&|]*f/i,
  /\bgit\s+branch\s+-D\b/,
  /\b(?:terraform|tofu)\s+destroy\b/i,
  /\b(?:kubectl\s+delete|helm\s+uninstall|prisma\s+migrate\s+reset|dropdb\b)/i,
];
if (destructive.some((pattern) => pattern.test(command))) {
  warnings.push("destructive command detected; confirm scope, authorization, and a recovery path before running it");
}
if (/\bgit\s+push\b|\b(?:npm|pnpm|yarn|bun)\s+(?:publish|unpublish)\b/i.test(command)) {
  warnings.push("external write detected; confirm explicit authorization and the intended remote, branch, or package");
}
if (/\b(?:kubectl\s+apply|helm\s+(?:install|upgrade)|terraform\s+apply|tofu\s+apply|vercel\s+deploy|netlify\s+deploy|fly\s+deploy)\b/i.test(command)) {
  warnings.push("deployment command detected; confirm the target environment, approval gate, monitoring, and recovery plan");
}
if (/(?:^|[\s"'])\.(?:env(?!\.(?:example|sample|template)\b)(?:\.[\w.-]+)?|npmrc)\b|credentials\.json\b|\.(?:pem|p12|pfx|key)\b/i.test(command)) {
  warnings.push("secret-bearing path referenced; avoid printing credentials or sending them to logs, prompts, or remote tools");
}
if (warnings.length) process.stderr.write("mstack risk review:\n" + warnings.map((item) => "- " + item).join("\n") + "\n");
process.stdout.write("{}\n");
