import type { HookDefinition, RuntimeAsset } from "../types.js";

function runtimeHookCommand(name: string): string {
  const loader = [
    "const f=require('node:fs'),p=require('node:path'),u=require('node:url')",
    "let d=process.cwd(),s",
    `for(;;){s=p.join(d,'.mstack','runtime','hooks','${name}.mjs');if(f.existsSync(s))break;const n=p.dirname(d);if(n===d)process.exit(0);d=n}`,
    "import(u.pathToFileURL(s).href)",
  ].join(";");
  return `node -e ${JSON.stringify(loader)}`;
}

const repositoryHealthScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

async function readInput() {
  let data = "";
  process.stdin.setEncoding("utf8");
  for await (const chunk of process.stdin) {
    data += chunk;
    if (data.length > 1_000_000) return {};
  }
  try { return data.trim() ? JSON.parse(data) : {}; } catch { return {}; }
}

function findRoot(start) {
  let current = resolve(start);
  while (true) {
    if (existsSync(join(current, ".git")) || existsSync(join(current, ".mstack"))) return current;
    const parent = dirname(current);
    if (parent === current) return resolve(start);
    current = parent;
  }
}

function hasTests(root) {
  const candidates = ["test", "tests", "spec", "__tests__"];
  if (candidates.some((name) => existsSync(join(root, name)))) return true;
  const sourceRoots = ["src", "app", "apps", "packages"].map((name) => join(root, name));
  const queue = sourceRoots.filter(existsSync);
  let inspected = 0;
  while (queue.length && inspected < 500) {
    const path = queue.pop();
    inspected += 1;
    let entries = [];
    try { entries = readdirSync(path); } catch { continue; }
    for (const entry of entries) {
      const child = join(path, entry);
      let stats;
      try { stats = statSync(child); } catch { continue; }
      if (stats.isDirectory() && entry !== "node_modules" && entry !== "dist") queue.push(child);
      if (stats.isFile() && /(?:\.test|\.spec)\.[cm]?[jt]sx?$/.test(entry)) return true;
    }
  }
  return false;
}

function hasTypeScript(root) {
  if (existsSync(join(root, "tsconfig.json"))) return true;
  const packages = join(root, "packages");
  if (!existsSync(packages)) return false;
  try {
    return readdirSync(packages).some((name) => existsSync(join(packages, name, "tsconfig.json")));
  } catch { return false; }
}

const input = await readInput();
const requestedCwd = input && typeof input === "object" && typeof input.cwd === "string" ? input.cwd : process.cwd();
const root = findRoot(requestedCwd);
const warnings = [];
const docs = join(root, "docs");
if (existsSync(join(root, ".mstack")) && !existsSync(docs)) {
  warnings.push("mstack is installed but docs/ is missing; add project-owned product and architecture context");
} else if (existsSync(docs)) {
  const markdown = readdirSync(docs).filter((name) => name.endsWith(".md"));
  if ((markdown.length || existsSync(join(root, ".mstack"))) && !existsSync(join(docs, "product.md"))) warnings.push("docs/ exists but docs/product.md is missing");
  if ((markdown.length || existsSync(join(root, ".mstack"))) && !existsSync(join(docs, "architecture.md"))) warnings.push("docs/ exists but docs/architecture.md is missing");
  for (const name of ["product.md", "architecture.md"]) {
    const path = join(docs, name);
    if (!existsSync(path)) continue;
    const content = readFileSync(path, "utf8");
    if (content.trim().length < 300) warnings.push("docs/" + name + " is too thin to guide material engineering decisions");
    if (/\{\{[^}]+\}\}/.test(content)) warnings.push("docs/" + name + " still contains unfilled template fields");
  }
}

const packagePath = join(root, "package.json");
if (existsSync(packagePath)) {
  try {
    const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
    const scripts = pkg.scripts || {};
    if (!scripts.test && hasTests(root)) warnings.push("tests exist but package.json has no test script");
    if (!scripts.build && (existsSync(join(root, "src")) || existsSync(join(root, "packages")))) warnings.push("source exists but package.json has no build script");
    if (!scripts.typecheck && !scripts.check && hasTypeScript(root)) warnings.push("TypeScript configuration exists but package.json has no typecheck or check script");
  } catch {
    warnings.push("package.json could not be parsed");
  }
}

const lockfiles = ["package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lock", "bun.lockb"].filter((name) => existsSync(join(root, name)));
if (lockfiles.length > 1) warnings.push("multiple JavaScript lockfiles found (" + lockfiles.join(", ") + "); keep one package-manager source of truth");

if (warnings.length) {
  process.stderr.write("mstack repository health:\n" + warnings.slice(0, 5).map((item) => "- " + item).join("\n") + "\n");
}
process.stdout.write("{}\n");
`;

const featureCompletenessScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";

function git(args, cwd, trim = true) {
  const result = spawnSync("git", args, { cwd, encoding: "utf8", maxBuffer: 2_000_000 });
  if (result.status !== 0) return "";
  return trim ? result.stdout.trim() : result.stdout;
}

function gitFileHashes(files, cwd) {
  const existing = [...new Set(files)].sort().filter((file) => existsSync(resolve(cwd, file)));
  const ordinary = existing.filter((file) => !file.includes("\n")).slice(0, 10_000);
  const result = spawnSync("git", ["hash-object", "--no-filters", "--stdin-paths"], {
    cwd,
    encoding: "utf8",
    input: ordinary.length ? ordinary.join("\n") + "\n" : "",
    maxBuffer: 1_000_000,
  });
  if (result.status !== 0) return [];
  const hashes = result.stdout.trim() ? result.stdout.trim().split("\n") : [];
  return ordinary.map((file, index) => [file, hashes[index] || "missing"]);
}

const root = git(["rev-parse", "--show-toplevel"]);
if (!root) { process.stdout.write("{}\n"); process.exit(0); }
const status = git(["status", "--porcelain=v1", "-z", "--untracked-files=all"], root, false);
if (!status) { process.stdout.write("{}\n"); process.exit(0); }
const records = status.split("\0");
const files = [];
for (let index = 0; index < records.length; index += 1) {
  const record = records[index];
  if (!record || record.length < 4) continue;
  const code = record.slice(0, 2);
  files.push(record.slice(3));
  if (/[RC]/.test(code) && records[index + 1]) files.push(records[index += 1]);
}
const fingerprintHash = createHash("sha256").update(status);
for (const [file, hashed] of gitFileHashes(files, root)) {
  fingerprintHash.update("\0" + file + "\0" + hashed);
}
const fingerprint = fingerprintHash.digest("hex");
const gitStatePath = git(["rev-parse", "--git-path", "mstack-runtime/feature-fingerprint"], root);
const statePath = gitStatePath ? resolve(root, gitStatePath) : "";
try {
  if (statePath && existsSync(statePath) && readFileSync(statePath, "utf8") === fingerprint) {
    process.stdout.write("{}\n"); process.exit(0);
  }
} catch { /* A read-only repository should not make the hook fail. */ }

const code = files.filter((file) => /\.(?:[cm]?[jt]sx?|py|go|rs|java|kt|rb|php|cs|swift)$/.test(file));
const tests = files.filter((file) => /(?:^|\/)(?:test|tests|spec|__tests__)(?:\/|$)|(?:\.test|\.spec)\./.test(file));
const warnings = [];
if (code.length >= 2 && tests.length === 0) warnings.push("multiple source files changed without a corresponding test change; confirm existing coverage is sufficient");
if (files.some((file) => /(?:contracts?|openapi|routes?|api|schema)/i.test(file)) && tests.length === 0) {
  warnings.push("a contract-facing path changed without a contract or integration test change");
}
if (files.some((file) => /(?:^|\/)(?:auth|authorization|permissions?|security|policies?)(?:[._/-]|$)/i.test(file)) && tests.length === 0) {
  warnings.push("an authorization or security path changed without a denial-path test change");
}
if (files.some((file) => /(?:migrations?|prisma\/schema|schema\.sql)/i.test(file))) {
  warnings.push("data schema changed; verify compatibility, backfill, and rollback/forward recovery");
}
if (files.some((file) => /(?:^|\/)(?:\.env(?:\.(?!example$|sample$|template$)[^/]+)?|credentials\.json|[^/]+\.(?:pem|p12|pfx|key))$/i.test(file))) {
  warnings.push("a potentially secret-bearing file changed; verify it is intentionally tracked and contains no credentials");
}
if (warnings.length) process.stderr.write("mstack feature completeness:\n" + warnings.map((item) => "- " + item).join("\n") + "\n");
try {
  if (statePath) { mkdirSync(dirname(statePath), { recursive: true }); writeFileSync(statePath, fingerprint); }
} catch { /* A read-only repository should not make the hook fail. */ }
process.stdout.write("{}\n");
`;

const changeDisciplineScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
async function readInput() {
  let data = "";
  process.stdin.setEncoding("utf8");
  for await (const chunk of process.stdin) {
    data += chunk;
    if (data.length > 1_000_000) return {};
  }
  try { return data.trim() ? JSON.parse(data) : {}; } catch { return {}; }
}

function findCommand(value, depth = 0) {
  if (depth > 5 || value == null) return "";
  if (typeof value === "string") return "";
  if (Array.isArray(value)) {
    for (const item of value) { const found = findCommand(item, depth + 1); if (found) return found; }
    return "";
  }
  if (typeof value === "object") {
    if (typeof value.command === "string") return value.command;
    for (const item of Object.values(value)) { const found = findCommand(item, depth + 1); if (found) return found; }
  }
  return "";
}

const input = await readInput();
const command = findCommand(input);
const warnings = [];
if (/\bgit\s+commit\b/.test(command)) {
  const match = command.match(/(?:^|\s)(?:-m|--message(?:=|\s+))\s*(?:"([^"]*)"|'([^']*)'|(\S+))/);
  const message = match ? (match[1] || match[2] || match[3] || "").trim() : "";
  if (message && (message.length < 12 || /^(?:fix|update|changes|wip|stuff)(?:\s+(?:it|things?))?[.!]?$/i.test(message))) {
    warnings.push("commit message is too vague; describe the behavior or reason changed");
  }
}
function changesDependencies(value) {
  if (/\b(?:pip\s+(?:install|uninstall)|cargo\s+(?:add|remove)|go\s+get)\b/.test(value)) return true;
  return value.split(/&&|\|\||;/).some((segment) => {
    const tokens = segment.trim().split(/\s+/);
    const manager = tokens.findIndex((token) => /^(?:npm|pnpm|yarn|bun)$/.test(token));
    if (manager < 0) return false;
    const action = tokens[manager + 1];
    if (["add", "remove", "rm", "uninstall"].includes(action)) return true;
    if (action !== "install" && action !== "i") return false;
    return tokens.slice(manager + 2).some((token) => !token.startsWith("-") && !/^(?:true|false)$/.test(token));
  });
}
if (changesDependencies(command)) {
  warnings.push("dependency change detected; verify necessity, lockfile, license/security posture, and runtime impact");
}
if (warnings.length) process.stderr.write("mstack change discipline:\n" + warnings.map((item) => "- " + item).join("\n") + "\n");
process.stdout.write("{}\n");
`;

const riskReviewScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
async function readInput() {
  let data = "";
  process.stdin.setEncoding("utf8");
  for await (const chunk of process.stdin) {
    data += chunk;
    if (data.length > 1_000_000) return {};
  }
  try { return data.trim() ? JSON.parse(data) : {}; } catch { return {}; }
}

function findCommand(value, depth = 0) {
  if (depth > 5 || value == null || typeof value === "string") return "";
  if (Array.isArray(value)) {
    for (const item of value) { const found = findCommand(item, depth + 1); if (found) return found; }
    return "";
  }
  if (typeof value === "object") {
    if (typeof value.command === "string") return value.command;
    for (const item of Object.values(value)) { const found = findCommand(item, depth + 1); if (found) return found; }
  }
  return "";
}

const input = await readInput();
const command = findCommand(input);
const warnings = [];
const destructive = [
  /\brm\s+(?:-[^\s;&|]*[rR][^\s;&|]*[fF]|-[^\s;&|]*[fF][^\s;&|]*[rR]|--recursive\b[^;&|]*--force\b|--force\b[^;&|]*--recursive\b)/,
  /\bgit\s+reset\s+--hard\b/i,
  /\bgit\s+clean\s+-[^\s;&|]*f/i,
  /\bgit\s+branch\s+-D\b/,
  /\b(?:terraform|tofu)\s+destroy\b/i,
  /\b(?:kubectl\s+delete|helm\s+uninstall|prisma\s+migrate\s+reset|dropdb\b)/i,
];
if (destructive.some((pattern) => pattern.test(command))) {
  warnings.push("destructive command detected; confirm scope, authorization, and a recovery path before running it");
}
if (/\bgit\s+push\b|\b(?:npm|pnpm|yarn|bun)\s+(?:publish|unpublish)\b/i.test(command)) {
  warnings.push("external write detected; confirm explicit authorization and the intended remote, branch, or package");
}
if (/\b(?:kubectl\s+apply|helm\s+(?:install|upgrade)|terraform\s+apply|tofu\s+apply|vercel\s+deploy|netlify\s+deploy|fly\s+deploy)\b/i.test(command)) {
  warnings.push("deployment command detected; confirm the target environment, approval gate, monitoring, and recovery plan");
}
if (/(?:^|[\s"'])\.(?:env(?!\.(?:example|sample|template)\b)(?:\.[\w.-]+)?|npmrc)\b|credentials\.json\b|\.(?:pem|p12|pfx|key)\b/i.test(command)) {
  warnings.push("secret-bearing path referenced; avoid printing credentials or sending them to logs, prompts, or remote tools");
}
if (warnings.length) process.stderr.write("mstack risk review:\n" + warnings.map((item) => "- " + item).join("\n") + "\n");
process.stdout.write("{}\n");
`;

export const engineeringHooks: readonly HookDefinition[] = [
  {
    id: "repository-health",
    version: "1.1.0",
    activation: "privileged",
    security: "executable",
    dependencies: ["repository-health-hook"],
    event: "session-start",
    command: runtimeHookCommand("repository-health"),
    timeoutMs: 5_000,
  },
  {
    id: "change-discipline",
    version: "1.1.0",
    activation: "privileged",
    security: "executable",
    dependencies: ["change-discipline-hook"],
    event: "before-tool",
    command: runtimeHookCommand("change-discipline"),
    timeoutMs: 2_000,
  },
  {
    id: "risk-review",
    version: "1.0.0",
    activation: "privileged",
    security: "executable",
    dependencies: ["risk-review-hook"],
    event: "before-tool",
    command: runtimeHookCommand("risk-review"),
    timeoutMs: 2_000,
  },
  {
    id: "feature-completeness",
    version: "1.1.0",
    activation: "privileged",
    security: "executable",
    dependencies: ["feature-completeness-hook"],
    event: "after-response",
    command: runtimeHookCommand("feature-completeness"),
    timeoutMs: 5_000,
  },
];

export const hookAssets: readonly RuntimeAsset[] = [
  {
    id: "repository-health-hook",
    version: "1.1.0",
    activation: "privileged",
    security: "executable",
    feature: "hooks",
    path: ".mstack/runtime/hooks/repository-health.mjs",
    content: repositoryHealthScript,
  },
  {
    id: "change-discipline-hook",
    version: "1.1.0",
    activation: "privileged",
    security: "executable",
    feature: "hooks",
    path: ".mstack/runtime/hooks/change-discipline.mjs",
    content: changeDisciplineScript,
  },
  {
    id: "risk-review-hook",
    version: "1.0.0",
    activation: "privileged",
    security: "executable",
    feature: "hooks",
    path: ".mstack/runtime/hooks/risk-review.mjs",
    content: riskReviewScript,
  },
  {
    id: "feature-completeness-hook",
    version: "1.1.0",
    activation: "privileged",
    security: "executable",
    feature: "hooks",
    path: ".mstack/runtime/hooks/feature-completeness.mjs",
    content: featureCompletenessScript,
  },
];
