import type { HookDefinition, RuntimeAsset } from "../types.js";

function runtimeHookCommand(name: string): string {
  const loader = [
    "const f=require('node:fs'),p=require('node:path'),u=require('node:url')",
    "let d=process.cwd(),s",
    `for(;;){s=p.join(d,'.mstack','runtime','hooks','${name}.mjs');if(f.existsSync(s))break;const n=p.dirname(d);if(n===d)process.exit(0);d=n}`,
    "import(u.pathToFileURL(s).href)",
  ].join(";");
  return `node -e ${JSON.stringify(loader)}`;
}

const repositoryHealthScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

function readInput() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => {
      try { resolve(data.trim() ? JSON.parse(data) : {}); } catch { resolve({}); }
    });
  });
}

function findRoot(start) {
  let current = resolve(start);
  while (true) {
    if (existsSync(join(current, ".git")) || existsSync(join(current, ".mstack"))) return current;
    const parent = dirname(current);
    if (parent === current) return resolve(start);
    current = parent;
  }
}

function hasTests(root) {
  const candidates = ["test", "tests", "spec", "__tests__"];
  if (candidates.some((name) => existsSync(join(root, name)))) return true;
  const sourceRoots = ["src", "app", "apps", "packages"].map((name) => join(root, name));
  const queue = sourceRoots.filter(existsSync);
  let inspected = 0;
  while (queue.length && inspected < 500) {
    const path = queue.pop();
    inspected += 1;
    let entries = [];
    try { entries = readdirSync(path); } catch { continue; }
    for (const entry of entries) {
      const child = join(path, entry);
      let stats;
      try { stats = statSync(child); } catch { continue; }
      if (stats.isDirectory() && entry !== "node_modules" && entry !== "dist") queue.push(child);
      if (stats.isFile() && /(?:\.test|\.spec)\.[cm]?[jt]sx?$/.test(entry)) return true;
    }
  }
  return false;
}

const input = await readInput();
const root = findRoot(typeof input.cwd === "string" ? input.cwd : process.cwd());
const warnings = [];
const docs = join(root, "docs");
if (existsSync(docs)) {
  const markdown = readdirSync(docs).filter((name) => name.endsWith(".md"));
  if (markdown.length && !existsSync(join(docs, "product.md"))) warnings.push("docs/ exists but docs/product.md is missing");
  if (markdown.length && !existsSync(join(docs, "architecture.md"))) warnings.push("docs/ exists but docs/architecture.md is missing");
  for (const name of ["product.md", "architecture.md"]) {
    const path = join(docs, name);
    if (!existsSync(path)) continue;
    const content = readFileSync(path, "utf8");
    if (content.trim().length < 300) warnings.push("docs/" + name + " is too thin to guide material engineering decisions");
    if (/\{\{[^}]+\}\}/.test(content)) warnings.push("docs/" + name + " still contains unfilled template fields");
  }
}

const packagePath = join(root, "package.json");
if (existsSync(packagePath)) {
  try {
    const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
    const scripts = pkg.scripts || {};
    if (!scripts.test && hasTests(root)) warnings.push("tests exist but package.json has no test script");
    if (!scripts.build && (existsSync(join(root, "src")) || existsSync(join(root, "packages")))) warnings.push("source exists but package.json has no build script");
  } catch {
    warnings.push("package.json could not be parsed");
  }
}

if (warnings.length) {
  process.stderr.write("mstack repository health:\n" + warnings.slice(0, 5).map((item) => "- " + item).join("\n") + "\n");
}
process.stdout.write("{}\n");
`;

const featureCompletenessScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { spawnSync } from "node:child_process";

function git(args) {
  const result = spawnSync("git", args, { encoding: "utf8" });
  return result.status === 0 ? result.stdout.trim() : "";
}

const root = git(["rev-parse", "--show-toplevel"]);
if (!root) { process.stdout.write("{}\n"); process.exit(0); }
const status = git(["status", "--porcelain=v1", "--untracked-files=all"]);
if (!status) { process.stdout.write("{}\n"); process.exit(0); }
const files = status.split("\n").map((line) => line.slice(3).trim()).filter(Boolean);
const fingerprint = createHash("sha256").update(files.sort().join("\n")).digest("hex");
const statePath = git(["rev-parse", "--git-path", "mstack-runtime/feature-fingerprint"]);
try {
  if (statePath && existsSync(statePath) && readFileSync(statePath, "utf8") === fingerprint) {
    process.stdout.write("{}\n"); process.exit(0);
  }
  if (statePath) { mkdirSync(dirname(statePath), { recursive: true }); writeFileSync(statePath, fingerprint); }
} catch { /* A read-only repository should not make the hook fail. */ }

const code = files.filter((file) => /\.(?:[cm]?[jt]sx?|py|go|rs|java|kt|rb|php|cs|swift)$/.test(file));
const tests = files.filter((file) => /(?:^|\/)(?:test|tests|spec|__tests__)(?:\/|$)|(?:\.test|\.spec)\./.test(file));
const warnings = [];
if (code.length >= 2 && tests.length === 0) warnings.push("multiple source files changed without a corresponding test change; confirm existing coverage is sufficient");
if (files.some((file) => /(?:contracts?|openapi|routes?|api|schema)/i.test(file)) && tests.length === 0) {
  warnings.push("a contract-facing path changed without a contract or integration test change");
}
if (files.some((file) => /(?:migrations?|prisma\/schema|schema\.sql)/i.test(file))) {
  warnings.push("data schema changed; verify compatibility, backfill, and rollback/forward recovery");
}
if (warnings.length) process.stderr.write("mstack feature completeness:\n" + warnings.map((item) => "- " + item).join("\n") + "\n");
process.stdout.write("{}\n");
`;

const changeDisciplineScript = String.raw`// Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.
function readInput() {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => {
      try { resolve(data.trim() ? JSON.parse(data) : {}); } catch { resolve({}); }
    });
  });
}

function findCommand(value, depth = 0) {
  if (depth > 5 || value == null) return "";
  if (typeof value === "string") return "";
  if (Array.isArray(value)) {
    for (const item of value) { const found = findCommand(item, depth + 1); if (found) return found; }
    return "";
  }
  if (typeof value === "object") {
    if (typeof value.command === "string") return value.command;
    for (const item of Object.values(value)) { const found = findCommand(item, depth + 1); if (found) return found; }
  }
  return "";
}

const input = await readInput();
const command = findCommand(input);
const warnings = [];
if (/\bgit\s+commit\b/.test(command)) {
  const match = command.match(/(?:-m|--message(?:=|\s+))\s*["']?([^"']+)/);
  const message = match ? match[1].trim() : "";
  if (message && (message.length < 12 || /^(?:fix|update|changes|wip|stuff)\b/i.test(message))) {
    warnings.push("commit message is too vague; describe the behavior or reason changed");
  }
}
function changesDependencies(value) {
  if (/\b(?:pip\s+install|cargo\s+add|go\s+get)\b/.test(value)) return true;
  return value.split(/&&|\|\||;/).some((segment) => {
    const tokens = segment.trim().split(/\s+/);
    const manager = tokens.findIndex((token) => /^(?:npm|pnpm|yarn|bun)$/.test(token));
    if (manager < 0) return false;
    const action = tokens[manager + 1];
    if (action === "add") return true;
    if (action !== "install" && action !== "i") return false;
    return tokens.slice(manager + 2).some((token) => !token.startsWith("-") && !/^(?:true|false)$/.test(token));
  });
}
if (changesDependencies(command)) {
  warnings.push("dependency change detected; verify necessity, lockfile, license/security posture, and runtime impact");
}
if (warnings.length) process.stderr.write("mstack change discipline:\n" + warnings.map((item) => "- " + item).join("\n") + "\n");
process.stdout.write("{}\n");
`;

export const engineeringHooks: readonly HookDefinition[] = [
  {
    id: "repository-health",
    event: "session-start",
    command: runtimeHookCommand("repository-health"),
    timeoutMs: 5_000,
  },
  {
    id: "change-discipline",
    event: "before-tool",
    command: runtimeHookCommand("change-discipline"),
    timeoutMs: 2_000,
  },
  {
    id: "feature-completeness",
    event: "after-response",
    command: runtimeHookCommand("feature-completeness"),
    timeoutMs: 5_000,
  },
];

export const hookAssets: readonly RuntimeAsset[] = [
  {
    feature: "hooks",
    path: ".mstack/runtime/hooks/repository-health.mjs",
    content: repositoryHealthScript,
  },
  {
    feature: "hooks",
    path: ".mstack/runtime/hooks/change-discipline.mjs",
    content: changeDisciplineScript,
  },
  {
    feature: "hooks",
    path: ".mstack/runtime/hooks/feature-completeness.mjs",
    content: featureCompletenessScript,
  },
];
