import type { PromptDefinition } from "../types.js";

interface PromptSource {
  readonly id: string;
  readonly description: string;
  readonly argumentHint: string;
  readonly task: string;
  readonly method: readonly string[];
  readonly deliverables: readonly string[];
  readonly constraints: readonly string[];
}

function definePrompt(source: PromptSource): PromptDefinition {
  return {
    id: source.id,
    version: "1.1.0",
    activation: "passive",
    security: "content",
    fallback: "degrade",
    description: source.description,
    argumentHint: source.argumentHint,
    prompt: [
      `# ${source.id}`,
      "",
      source.task,
      "",
      "This prompt follows Misbah Khursheed's Build Like This workflow: establish the user outcome and reasoning before generating implementation, then preserve that reasoning in contracts, boundaries, tests, and documentation.",
      "",
      "## Project identity and sources of truth",
      "",
      "The repository where this prompt is installed is the host project being built. Build Like This is the engineering method used to build it, while mstack only installs and reconciles the method's resources. Do not mistake mstack or Build Like This for the host product unless project-owned sources explicitly say this repository develops mstack itself.",
      "",
      "Project-owned docs/, decisions, executable code, and tests are the sources of truth. .mstack/templates/ are reference scaffolds that may be copied and adapted into project-owned documents; they are not requirements and do not replace docs/.",
      "",
      "Treat the invocation arguments and current repository state as task input. Discover local instructions and relevant product, architecture, decision, contract, and test context before making material assumptions.",
      "",
      "## Method",
      "",
      ...source.method.map((item, index) => `${index + 1}. ${item}`),
      "",
      "## Deliverables",
      "",
      ...source.deliverables.map((item) => `- ${item}`),
      "",
      "## Constraints",
      "",
      ...source.constraints.map((item) => `- ${item}`),
      "",
      "## Delegation and parallel safety",
      "",
      "- For a material lifecycle task, the active lead must delegate at least one bounded specialist lane when subagents are available; prefer two or more concurrent lanes only when their evidence or file ownership is independent.",
      "- The active lead owns acceptance criteria and final integration. Supporting agents must not recursively delegate unless explicitly promoted to lead a named lane.",
      "- Give each delegate distinct inputs, outputs, and ownership. Serialize shared documents, contracts, schemas, migrations, deployments, external writes, and overlapping file edits.",
      "- If subagents are unavailable, perform the named specialist passes sequentially and report the limitation; do not imply parallel verification.",
      "- Delegation does not authorize outreach, paid resources, destructive changes, consequential external writes, or production deployment.",
      "",
      "Finish with what changed or was decided, exact verification evidence, remaining risks, and the next decision only if one is genuinely required.",
    ].join("\n"),
  };
}

export const engineeringPrompts: readonly PromptDefinition[] = [
  definePrompt({
    id: "build-feature",
    description: "Deliver a bounded feature from user outcome through verified implementation and rollout notes.",
    argumentHint: "<feature request or specification>",
    task: "Build the requested feature as the narrowest complete vertical slice, preserving existing behavior outside the agreed scope.",
    method: [
      "Restate the user outcome, evidence/assumptions, scope, non-goals, acceptance criteria, and affected actors.",
      "Inspect current behavior and identify contract, data, authorization, security, accessibility, operational, and documentation impact.",
      "Resolve or expose decisions that materially change the implementation; avoid blocking on discoverable details.",
      "Define backend/public contracts and state transitions before integrating clients; plan compatibility and migration where needed.",
      "Implement by owning capability with validated boundaries, complete failure states, and no unrelated refactoring.",
      "Test important success, validation, denial, failure, retry/concurrency, and recovery paths at the appropriate levels.",
      "Run relevant type, build, lint, test, and focused operational checks; review the final diff against acceptance criteria.",
    ],
    deliverables: [
      "Working implementation and focused tests, not merely a plan or scaffold.",
      "Explicit contract/data/configuration/migration changes and compatibility behavior.",
      "Verification results plus rollout, observability, and rollback/forward-recovery notes where relevant.",
    ],
    constraints: [
      "Do not invent product behavior to fill consequential ambiguity.",
      "Do not make client checks the source of truth for authorization or business invariants.",
      "Do not claim completion while acceptance criteria or required verification remain unresolved.",
    ],
  }),
  definePrompt({
    id: "plan-mvp",
    description: "Shape a product hypothesis into the smallest measurable MVP and implementation sequence.",
    argumentHint: "<product idea, users, evidence, constraints>",
    task: "Plan an MVP that tests the highest-risk product assumption with the least product and operational complexity.",
    method: [
      "Separate known evidence, assumptions, and open questions; identify the target user and painful current behavior.",
      "Define the outcome and falsifiable success signal before proposing features.",
      "Map the minimum end-to-end journey and all user-visible states needed for a trustworthy experience.",
      "Rank assumptions by impact and uncertainty; choose scope that tests the riskiest one without speculative platform work.",
      "Define non-goals, permissions, data/privacy boundaries, operational constraints, and explicit kill/revisit criteria.",
      "Translate scope into vertical delivery slices with acceptance criteria and a validation/rollout plan.",
    ],
    deliverables: [
      "Problem/evidence/assumption ledger and target outcome metric.",
      "MVP journey, scope, non-goals, acceptance criteria, and failure/degraded behavior.",
      "Ordered delivery and learning plan with risks, cost/operations considerations, and next-stage triggers.",
    ],
    constraints: [
      "Do not substitute feature count or launch date for a user outcome.",
      "Do not include multi-tenant scale, extensibility, or integrations without an MVP requirement.",
      "Do not present fabricated market evidence or metrics as fact.",
    ],
  }),
  definePrompt({
    id: "review-architecture",
    description: "Assess architecture against current requirements and recommend evidence-backed decisions.",
    argumentHint: "<system, proposal, or architecture concern>",
    task: "Review the relevant architecture as an owner: test whether boundaries, data, contracts, and operations fit the documented requirements and change pressure.",
    method: [
      "Map actors, components, data ownership, trust boundaries, dependency direction, and key flows from documents and code.",
      "Trace representative success, failure, retry, migration, and recovery journeys end to end.",
      "Evaluate cohesion/coupling, consistency, security/isolation, availability, observability, deployment safety, scale, and cost.",
      "Distinguish present defects from future risks and validate claims against load, incidents, or concrete change scenarios.",
      "Compare the smallest viable options; state consequences, migration cost, and conditions that would justify added complexity.",
      "Identify decisions that belong in an ADR and the evidence needed to validate them.",
    ],
    deliverables: [
      "Concise current-state map and requirements-fit assessment.",
      "Prioritized strengths/risks with concrete failure scenarios and evidence.",
      "Recommended decisions, alternatives rejected, migration/recovery approach, and revisit triggers.",
    ],
    constraints: [
      "Do not recommend services, queues, caches, or new technology as architectural decoration.",
      "Do not accept diagrams as truth when executable behavior contradicts them.",
      "Do not rewrite the system when a module boundary or contract correction is sufficient.",
    ],
  }),
  definePrompt({
    id: "review-pull-request",
    description: "Review a change for correctness, security, compatibility, operations, and missing tests.",
    argumentHint: "<PR, branch, diff, or review focus>",
    task: "Review the specified change. Findings are the product: report only defects or material risks that the author can act on.",
    method: [
      "Read the change intent and acceptance criteria, then inspect the full diff and relevant surrounding behavior.",
      "Trace changed paths through success, validation, authorization, boundary, failure, concurrency, and recovery scenarios.",
      "Check contracts, migrations, configuration, secrets, compatibility, observability, and rollout implications.",
      "Assess tests against the changed invariants and high-risk paths; run focused verification where safe.",
      "For each candidate finding, confirm a plausible failure scenario, impact, and precise code evidence.",
      "Order findings by severity and omit style commentary without concrete maintenance or correctness impact.",
    ],
    deliverables: [
      "Findings first; each includes severity, location, failure scenario, impact, and narrow remediation.",
      "Open questions only where missing information changes correctness or safety.",
      "Verification performed, remaining coverage gaps, and residual risks; explicitly say when no findings remain.",
    ],
    constraints: [
      "Do not implement fixes unless explicitly asked after the review.",
      "Do not inflate severity or report speculative defects without a causal path.",
      "Do not let passing tests override a demonstrated untested failure.",
    ],
  }),
  definePrompt({
    id: "debug-failure",
    description: "Diagnose a failure through reproduction and controlled evidence before implementing a fix.",
    argumentHint: "<symptom, error, reproduction, environment>",
    task: "Debug the reported failure systematically and, when authorized, implement the narrowest root-cause fix with regression evidence.",
    method: [
      "Capture expected/actual behavior, environment, exact input, frequency, timing, and last-known-good state.",
      "Separate observations from hypotheses and build the smallest reliable reproduction.",
      "Trace backward from the symptom to the first violated invariant across process, network, data, and UI boundaries.",
      "Rank hypotheses and run one discriminating experiment at a time; preserve logs/traces that eliminate branches.",
      "Explain the causal mechanism before changing behavior, then fix the broken invariant rather than masking the symptom.",
      "Add a regression test that fails for the original reason and verify adjacent and production-different paths.",
    ],
    deliverables: [
      "Minimal reproduction, evidence timeline, and tested hypothesis ledger.",
      "Root-cause explanation linking the broken invariant to the symptom.",
      "Narrow fix and regression test when requested, plus verification and monitoring/data-repair needs.",
    ],
    constraints: [
      "Do not suppress errors, loosen validation, or weaken tests to make the symptom disappear.",
      "Do not mutate external or production state without explicit authorization and recovery planning.",
      "Do not call correlation a root cause.",
    ],
  }),
  definePrompt({
    id: "refactor-module",
    description: "Refactor a module through small behavior-preserving transformations and a clear safety net.",
    argumentHint: "<module, maintenance pain, desired boundary>",
    task: "Improve the requested module's structure without changing its observable behavior or expanding adjacent scope.",
    method: [
      "Name the concrete change pain, responsibility/coupling problem, preserved invariants, and success signal.",
      "Map callers, dependencies, side effects, contracts, ownership, and current test evidence.",
      "Add characterization tests for important behavior that lacks a practical safety net.",
      "Design and apply a sequence of small compiling/testable transformations toward the owning boundary.",
      "Remove obsolete paths only after callers migrate; resist abstractions without stable shared semantics.",
      "Compare before/after dependencies and run focused plus broader regression checks.",
    ],
    deliverables: [
      "Refactored code with behavior-preserving tests and no unrelated semantic changes.",
      "Short before/after explanation of responsibilities and dependency direction.",
      "Verification evidence and intentionally deferred cleanup.",
    ],
    constraints: [
      "Do not mix dependency upgrades or feature behavior into the structural change.",
      "Do not optimize for line/file count over cohesion and readability.",
      "Do not create a generic abstraction solely to remove superficial duplication.",
    ],
  }),
  definePrompt({
    id: "design-api",
    description: "Design an implementation-ready API with schemas, permissions, errors, and compatibility rules.",
    argumentHint: "<user operation, resources, clients, constraints>",
    task: "Design the requested API contract before implementation so clients and servers can work against the same validated behavior.",
    method: [
      "Define the user operation, actors, resource ownership, invariants, and state transitions in domain language.",
      "Choose operation/resource shape consistent with existing API conventions, not database tables or screens.",
      "Specify authentication and resource authorization independently for every operation.",
      "Define request and response schemas, normalization, bounds, pagination, idempotency, concurrency, and rate limits.",
      "Define stable errors and safe details for validation, denial, conflict, missing resources, rate limits, and dependency failure.",
      "Write success/failure examples, compatibility/versioning behavior, observability, and contract tests.",
    ],
    deliverables: [
      "Operation table with actor, permission, request, response, state effect, and errors.",
      "Runtime-validatable schema or equivalent contract plus representative examples.",
      "Compatibility, idempotency/concurrency, rate-limit, security, and contract-test notes.",
    ],
    constraints: [
      "Do not leak database models, internal exceptions, secrets, or provider payloads.",
      "Do not rely on client validation for server invariants.",
      "Do not introduce breaking changes without a migration/deprecation path.",
    ],
  }),
  definePrompt({
    id: "improve-documentation",
    description: "Make project documentation accurate, decision-oriented, navigable, and verifiable against code.",
    argumentHint: "<document, audience, problem, or changed behavior>",
    task: "Improve the requested documentation as an operational source of truth, not as promotional prose or a dump of implementation detail.",
    method: [
      "Identify the audience, decision/task they need to complete, and authoritative executable sources.",
      "Verify commands, paths, contracts, defaults, examples, and current behavior against the repository.",
      "Separate product intent, current architecture, historical decisions, procedures, and reference material.",
      "Structure for progressive disclosure: outcome and prerequisites first, exact procedure/contract next, caveats and recovery last.",
      "Replace vague claims with concrete examples, failure behavior, ownership, and links to a single source of truth.",
      "Check link/path validity, command safety, terminology consistency, and stale duplication.",
    ],
    deliverables: [
      "Updated content optimized for the named audience and task.",
      "List of behavior/commands verified and any discrepancies found in code or other sources.",
      "Remaining unknowns or ownership decisions that documentation alone cannot resolve.",
    ],
    constraints: [
      "Do not describe behavior that was not verified or clearly label it as proposed.",
      "Do not duplicate whole contracts or decisions when a stable link is sufficient.",
      "Do not hide dangerous steps, prerequisites, failure modes, or recovery actions.",
    ],
  }),
  definePrompt({
    id: "production-readiness",
    description: "Assess whether a system or change is safe to operate and release under real failure conditions.",
    argumentHint: "<service, feature, or release scope>",
    task: "Perform an evidence-based production readiness review and produce a go/no-go decision with an actionable recovery-aware plan.",
    method: [
      "Confirm scope, acceptance criteria, owners, traffic/data assumptions, SLOs, and consequential user actions.",
      "Review authentication/authorization, data protection, abuse controls, dependencies, timeouts, retries, and idempotency.",
      "Trace startup, normal operation, overload, partial dependency failure, deploy, migration, backup/restore, and incident recovery.",
      "Verify build/tests/configuration/secrets, health/readiness, logs/metrics/traces, alerts, dashboards, and cost/capacity limits.",
      "Assess compatibility, rollout sequencing, smoke tests, feature controls, and rollback versus forward-recovery safety.",
      "Classify blockers, accepted risks, and follow-ups with named evidence, threshold, and owner.",
    ],
    deliverables: [
      "Go/no-go recommendation with blockers first and evidence for each readiness area.",
      "Progressive rollout, smoke test, monitoring thresholds, and rollback/forward-recovery procedure.",
      "Accepted residual risks, owners, incident/support notes, and post-release verification.",
    ],
    constraints: [
      "Do not mark readiness based on planned controls or commands that were not run.",
      "Do not recommend blind retries, fail-open security, or rollback across incompatible data migrations.",
      "Do not bury a high-impact operational gap in a checklist score.",
    ],
  }),
  definePrompt({
    id: "research-idea",
    description: "Research a product idea, test its riskiest assumptions, and recommend go, refine, or stop before MVP planning.",
    argumentHint: "<idea, suspected user/problem, evidence, constraints>",
    task: "Run Phase 1 with the idea-validation skill. The product-manager leads and delegates independent evidence lanes to product-researcher and product-analyst; determine whether the idea merits deeper user discovery without inventing validation.",
    method: [
      "State the falsifiable problem/value hypothesis, suspected user/context, decision options, current evidence, unknowns, and disconfirming signals.",
      "Inspect project-owned docs and existing evidence, then search independent current source classes with citations, dates, access dates, and limitations.",
      "Analyze current workarounds, alternatives, switching costs, frequency/severity signals, feasibility constraints, and evidence against the idea.",
      "Separate facts, interpretations, assumptions, contradictions, and unanswered questions; treat secondary evidence as hypothesis-shaping rather than user validation.",
      "Make a go/refine/stop recommendation tied to an explicit evidence threshold and the cost of being wrong.",
      "Create or update a dated docs/research/ discovery brief and define the smallest authorized primary-research or experiment step.",
    ],
    deliverables: [
      "Cited discovery brief, alternative map, and evidence/assumption/contradiction ledger.",
      "Go/refine/stop decision with confidence, rationale, constraints, and explicit non-conclusions.",
      "Next validation plan with method, owner, authorization/privacy boundary, threshold, and stop rule.",
    ],
    constraints: [
      "Do not jump to features, MVP scope, architecture, or implementation before the idea clears its evidence gate.",
      "Do not fabricate sources, users, quotes, demand, market size, metrics, or certainty.",
      "Do not contact people, buy data, create accounts, or mutate external systems without explicit authorization.",
    ],
  }),
  definePrompt({
    id: "identify-target-users",
    description: "Define the narrow primary user segment, affected actors, exclusions, and evidence gaps for a validated idea.",
    argumentHint: "<validated problem, candidate users, evidence, launch constraints>",
    task: "Run Phase 2 with the target-user-definition skill. The product-manager leads while product-researcher and user-researcher independently test segment evidence and actor/context differences.",
    method: [
      "Confirm the validated problem direction and gather existing evidence about candidate users, contexts, workarounds, constraints, and alternatives.",
      "Segment only on differences in job, trigger, behavior, authority, constraints, consequence, or definition of success.",
      "Distinguish end users, buyers, administrators, operators, approvers, data subjects, and other actors whose incentives or permissions differ.",
      "Compare candidate segments by evidence strength, pain/frequency, reachability, switching cost, risk, and first-release constraints without inventing scores.",
      "Choose one narrow primary segment, name secondary actors and explicit exclusions, and explain what evidence would change the choice.",
      "Record the decision in project-owned research/product notes and define the next ethical sampling step for weak coverage.",
    ],
    deliverables: [
      "Primary-segment definition with context, job, trigger, workaround, constraints, desired success, and cited evidence.",
      "Actor/authority map plus secondary users, first-release exclusions, and decision rationale.",
      "Coverage and assumption ledger with a focused research sampling plan.",
    ],
    constraints: [
      "Do not create decorative personas or use demographics that change no product decision.",
      "Do not collapse user, buyer, approver, operator, and subject into one role when authority or outcomes differ.",
      "Do not claim representativeness, prevalence, or access to participants without evidence and authorization.",
    ],
  }),
  definePrompt({
    id: "research-user-needs",
    description: "Research the selected users' jobs, workarounds, pain, constraints, and desired outcomes before solution design.",
    argumentHint: "<target segment, open need questions, available evidence/access>",
    task: "Run Phase 3 with the user-needs-research skill. The user-researcher leads and separates existing-evidence analysis from research-method and coverage review.",
    method: [
      "Define the product decisions this research must inform, research questions, sampling gaps, disconfirming cases, method, and stopping criteria.",
      "Inspect authorized existing evidence and plan any primary research with explicit consent, privacy, retention, accessibility, and outreach boundaries.",
      "Investigate triggers, jobs, current steps, workarounds, frequency, severity, consequences, authority, constraints, and definitions of success.",
      "Keep observations/quotes traceable and distinguish observed behavior, stated preference, researcher interpretation, and product implication.",
      "Synthesize recurring patterns alongside negative and edge cases; label confidence, sample/coverage limits, and contradictions.",
      "Update project-owned docs/research/ artifacts and hand off prioritized opportunity statements rather than requested features.",
    ],
    deliverables: [
      "Research plan and/or synthesis with method, source/participant coverage, consent limits, dates, and confidence.",
      "Evidence-backed jobs, needs, workarounds, pain patterns, desired outcomes, and disconfirming cases.",
      "Prioritized opportunity statements, unanswered questions, and the next validation step.",
    ],
    constraints: [
      "Do not invent participants, interviews, quotes, observations, consent, prevalence, or findings.",
      "Do not perform outreach, recording, or personal-data collection without explicit authorization and safeguards.",
      "Do not translate a feature request into a requirement without understanding the underlying job and outcome.",
    ],
  }),
  definePrompt({
    id: "design-features",
    description: "Design the smallest coherent capability and accessible journey that addresses validated user needs.",
    argumentHint: "<validated needs, desired outcome, constraints, existing product>",
    task: "Run Phase 4 with the feature-design skill. The product-manager leads, product-designer explores journeys, and relevant architecture/security specialists review feasibility and risk without taking over product scope.",
    method: [
      "Restate validated needs, intended outcome, evidence, constraints, success criteria, and non-goals before suggesting solutions.",
      "Generate bounded alternative capabilities and flows, then compare need fit, behavior change, accessibility, complexity, risk, reversibility, and learning value.",
      "Select the narrowest coherent end-to-end journey and specify all success, loading, empty, validation, denial, degraded, failure, and recovery states.",
      "Identify actor/permission, data, contract, privacy/security, content, instrumentation, operational, and accessibility implications.",
      "Prototype and test the riskiest interaction or assumption at the lowest useful fidelity using only authorized evidence.",
      "Document the chosen behavior, rejected alternatives, non-goals, open contract questions, and testable acceptance criteria for product definition.",
    ],
    deliverables: [
      "Selected capability and alternative rationale mapped directly to validated needs and outcome.",
      "Complete user journey/state model with accessibility, permissions, content, failure, and recovery intent.",
      "Prototype/test evidence, behavioral acceptance criteria, non-goals, and unresolved implementation-boundary questions.",
    ],
    constraints: [
      "Do not treat a polished interface, stakeholder preference, or familiar pattern as evidence of need fit.",
      "Do not make UI checks the source of truth for authorization, financial state, or durable business rules.",
      "Do not include speculative platform work, personalization, or adjacent personas in the first capability.",
    ],
  }),
  definePrompt({
    id: "write-product-definition",
    description: "Write the authoritative product definition from validated evidence, decisions, scope, and measurable outcomes.",
    argumentHint: "<idea/user/needs/feature decisions and project context>",
    task: "Run Phase 5 with the product-definition skill. The product-manager leads while research and product-analysis lanes verify evidence traceability and metric operability; update product intent rather than merely improving documentation prose.",
    method: [
      "Reconcile project-owned product/feature documents with research decisions and shipped behavior; surface conflicts and stale sources explicitly.",
      "Define the primary user, current problem, evidence versus assumptions, intended observable outcome, constraints, and decision owner.",
      "Set first-release scope, non-goals, excluded users, complete user journey, policy boundaries, failure/recovery behavior, and acceptance criteria.",
      "Define success and guardrail metrics by formula, source, population, baseline, target, window, owner, and decision threshold.",
      "Update docs/product.md and any necessary docs/features.md or feature spec, preserving links to research rather than duplicating unsupported claims.",
      "Create a product-to-architecture handoff and block architecture only on unresolved decisions that materially change system design.",
    ],
    deliverables: [
      "Updated authoritative product/feature documentation with evidence-linked outcome, scope, non-goals, journey, constraints, and acceptance criteria.",
      "Operational metric definitions and assumption/open-decision ledger with owners and validation dates.",
      "Architecture handoff covering actors, risk, constraints, expected load/reliability, data/privacy, and remaining gates.",
    ],
    constraints: [
      "Do not invent evidence, baselines, targets, owners, deadlines, legal policy, or commercial constraints.",
      "Do not put frameworks, databases, folder structures, or internal components in product.md.",
      "Do not silently promote an unvalidated hypothesis to committed product scope.",
    ],
  }),
  definePrompt({
    id: "design-architecture",
    description: "Design the smallest implementation-ready architecture for the agreed product and record consequential decisions.",
    argumentHint: "<defined product/feature, current system, technical constraints>",
    task: "Run Phase 6 with the architecture-design skill. The software-architect leads and delegates database, security, and DevOps lanes; this creates the intended design, while review-architecture remains an assessment workflow.",
    method: [
      "Read the defined product outcomes, non-goals, journeys, acceptance criteria, constraints, current architecture/code, and relevant decisions.",
      "Map actors, trust boundaries, modules, ownership, data, critical flows, dependencies, external effects, and failure paths.",
      "Compare the smallest viable options against security, reliability, scale, cost, compatibility, and team operability; prefer a modular monolith absent measured need.",
      "Define module interfaces, dependency direction, contracts, schemas, permissions, state transitions, transaction/idempotency behavior, and migration compatibility.",
      "Define deployment/configuration, observability, capacity triggers, security controls, degradation, rollback/forward recovery, and validation evidence.",
      "Update docs/architecture.md and create an ADR for consequential choices with alternatives, consequences, rollout, and revisit triggers.",
    ],
    deliverables: [
      "Implementation-ready architecture with ownership, interactions, data, contracts, trust boundaries, failures, and operational behavior.",
      "Updated architecture source plus necessary ADR/API/schema decisions and rejected-option rationale.",
      "Sequenced backend/frontend/deployment handoff with tests, migrations, rollout/recovery, risks, and revisit triggers.",
    ],
    constraints: [
      "Do not add services, queues, caches, technologies, or generic abstractions without a requirement-linked reason.",
      "Do not leak database or vendor SDK types across domain or public boundaries.",
      "Do not conceal unresolved product, permission, data, security, or recovery decisions behind a diagram.",
    ],
  }),
  definePrompt({
    id: "build-backend",
    description: "Implement and verify the agreed backend slice, including contracts, authorization, persistence, failures, and operations.",
    argumentHint: "<feature/backend scope, agreed contracts, acceptance criteria>",
    task: "Run Phase 7 with the backend-delivery skill. The backend-engineer leads and delegates database, security, and independent test/contract lanes, with ai-engineer included only when an AI boundary exists.",
    method: [
      "Confirm agreed product/architecture behavior, actors, permissions, contracts, state transitions, errors, compatibility, and acceptance criteria.",
      "Resolve contract/document conflicts before coding and define runtime-validated schemas, authorization, invariants, transactions, idempotency, and stable errors.",
      "Implement the domain/application vertical slice behind cohesive module interfaces, then connect persistence and provider adapters with safe timeouts/recovery.",
      "Keep transport handlers thin, vendor/ORM types behind infrastructure boundaries, and logs/metrics useful but free of secrets and unnecessary personal data.",
      "Test success, validation bounds, authentication/authorization, tenant/resource isolation, duplicates/concurrency, dependency failure, and recovery at appropriate levels.",
      "Run relevant formatter, strict types, lint, tests, and production build; document migrations, configuration, rollout/recovery, and frontend contract examples.",
    ],
    deliverables: [
      "Working backend vertical slice with validated stable contracts, server-owned invariants, permissions, errors, and compatibility.",
      "Focused unit/integration/contract/security/recovery tests and exact verification results.",
      "Frontend handoff plus migration, observability, configuration, rollout, recovery, and residual-risk notes.",
    ],
    constraints: [
      "Do not place domain rules in routes, jobs, ORM models, callbacks, or UI clients.",
      "Do not expose secrets, stack traces, database internals, vendor payloads, or unnecessary personal data.",
      "Do not edit applied migration history or break existing consumers without a documented compatible path.",
    ],
  }),
  definePrompt({
    id: "build-frontend",
    description: "Implement and verify the complete accessible frontend journey against the agreed backend contract.",
    argumentHint: "<feature/frontend scope, design, contract, acceptance criteria>",
    task: "Run Phase 8 with the frontend-delivery skill. The frontend-engineer leads and delegates product-design/accessibility, independent journey testing, and performance lanes.",
    method: [
      "Confirm the approved journey, content, full state model, accessibility target, backend contract, browser/device support, and acceptance criteria.",
      "Model ownership of server, form, URL, and local presentation state before component boundaries; use a faithful typed mock only when backend integration is unavailable.",
      "Implement semantic, responsive, keyboard-accessible behavior for loading, empty, success, validation, denial, degraded, failure, and recovery states.",
      "Integrate faithfully with server contracts and surface discrepancies; do not duplicate authorization or durable business rules as client truth.",
      "Verify focus, screen-reader semantics, contrast, reduced motion, slow/offline/dependency behavior, critical browsers, and performance budgets.",
      "Run relevant formatter, strict types, lint, component/integration/end-to-end tests, and production build; record release assumptions and limitations.",
    ],
    deliverables: [
      "Working complete frontend journey with accessible semantics, deliberate state ownership, and faithful contract integration.",
      "Focused component/integration/end-to-end/accessibility/performance verification with exact results.",
      "Contract discrepancies, browser/device caveats, rollout implications, and residual-risk handoff.",
    ],
    constraints: [
      "Do not invent backend payloads or make client code authoritative for permissions, pricing, or critical state.",
      "Do not ship only the happy path or inaccessible custom controls where semantic platform behavior exists.",
      "Do not use motion unless it aids comprehension and respects reduced-motion behavior.",
    ],
  }),
  definePrompt({
    id: "deploy-product",
    description: "Execute an explicitly authorized progressive release with evidence gates, monitoring, communication, and recovery.",
    argumentHint: "<authorized environment, artifact/release, window, owners>",
    task: "Run Phase 9 with the deployment-delivery skill. The release-manager leads parallel preflight evidence lanes for DevOps, security, testing, and conditional database review, then serializes all stateful release actions.",
    method: [
      "Verify explicit authorization for the exact environment and operations, artifact identity, release scope, accountable owners, change window, and communication path.",
      "Collect successful acceptance/build/test/security/readiness evidence and confirm compatibility, dependency health, configuration/secrets, backups, and recovery capability.",
      "Publish and rehearse the ordered migration/deployment/feature-control sequence with smoke checks, metrics, stop thresholds, decision authority, and rollback/forward recovery.",
      "Execute only authorized actions stage by stage, recording versions, timestamps, command results, observations, communications, and gate decisions.",
      "Monitor product/system guardrails through progressive exposure; stop and recover when a predeclared threshold is crossed.",
      "Complete post-release verification, support/incident handoff, release record, residual-risk ownership, and improvement review date.",
    ],
    deliverables: [
      "Authorization and go/no-go record tied to exact target, artifact, evidence, owners, and accepted risks.",
      "Executed release log with migration/deployment stages, smoke checks, monitoring, communication, and recovery actions.",
      "Post-release outcome/system checks, incidents, residual risks, owners, and measurement handoff.",
    ],
    constraints: [
      "Do not infer production authorization from repository access, prompt invocation without a named target, or a passing readiness review.",
      "Do not parallelize migrations, deployments, feature-state changes, or other shared-state actions whose order affects safety.",
      "Do not expose secrets or use rollback when incompatible data changes require forward recovery.",
    ],
  }),
  definePrompt({
    id: "improve-product",
    description: "Measure released product outcomes and select one evidence-backed next experiment, refinement, expansion, or stop decision.",
    argumentHint: "<released scope, outcome metrics, evidence window, known issues>",
    task: "Run Phase 10 with the continuous-improvement skill. The product-manager leads, product-analyst validates measurement, and affected research, test, security, performance, or operations specialists investigate independent signals.",
    method: [
      "Restate the released hypothesis, target users, scope, baseline/target/window, decision thresholds, guardrails, and residual risks.",
      "Validate event/metric definitions, data lineage, exposure, baseline comparability, missingness, segment mix, and instrumentation quality before analysis.",
      "Compare outcome and diagnostic measures by relevant segment alongside user research/support, incidents, reliability, performance, cost, security, and accessibility evidence.",
      "Distinguish adoption, usability, value, reliability, and measurement failures; state plausible explanations, contradictions, and uncertainty without claiming causality.",
      "Choose continue/refine/expand/stop and rank opportunities by evidence, user outcome, risk, effort, and learning value.",
      "Update project-owned product/research/experiment/feature artifacts and define one smallest next experiment or vertical slice with owner, threshold, and review date.",
    ],
    deliverables: [
      "Outcome review with validated metrics, qualitative/operational evidence, guardrails, segment context, and uncertainty.",
      "Continue/refine/expand/stop decision with evidence-linked rationale, causal hypotheses, and accepted risks.",
      "One prioritized next experiment or slice with scope/non-goals, owner, acceptance threshold, verification, and review date.",
    ],
    constraints: [
      "Do not fabricate telemetry, baselines, causal certainty, user consensus, or statistical significance.",
      "Do not optimize a proxy while user harm, reliability, security, privacy, accessibility, or cost guardrails regress.",
      "Do not absorb unrelated cleanup or roadmap ideas without a demonstrated outcome or maintenance need.",
    ],
  }),
];
