import type { RuntimeAsset } from "../types.js";

const marker = "<!-- Generated by mstack. Regenerate instead of editing. -->";

function template(name: string, content: string): RuntimeAsset {
  return {
    feature: "repository-onboarding",
    path: `.mstack/templates/${name}.template.md`,
    content: `${marker}\n\n${content.trim()}`,
  };
}

export const runtimeTemplates: readonly RuntimeAsset[] = [
  template(
    "repository",
    `# {{project_name}} Repository Blueprint

## Purpose

- Product outcome this repository owns: {{outcome}}
- Primary users/operators: {{actors}}
- Explicit non-goals: {{non_goals}}

## Executable entry points

| Entry point | Responsibility | Inputs/outputs | Owner |
| --- | --- | --- | --- |
| {{path_or_command}} | {{single responsibility}} | {{contract}} | {{team_or_role}} |

## Module boundaries

| Module/package | Owns | Public interface | May depend on | Must not depend on |
| --- | --- | --- | --- | --- |
| {{module}} | {{behavior_or_data}} | {{exports_or_contract}} | {{allowed}} | {{forbidden}} |

Prefer organization by product capability. Keep domain behavior independent from HTTP, UI, persistence, and vendor SDKs where that boundary makes behavior easier to test or change.

## Required repository surfaces

- \`README.md\`: fast orientation and links, not the full source of truth.
- \`docs/product.md\`: users, problem, outcome, scope, non-goals, success.
- \`docs/architecture.md\`: current boundaries, contracts, data, operations, security.
- \`docs/decisions/\`: consequential decision history.
- Agent instructions: setup, verification, ownership, and safety constraints.
- Repeatable commands for install, build, typecheck, test, lint/format, and release checks.

## Developer workflow

1. Prerequisites: {{runtime_and_services}}
2. Install: \`{{install_command}}\`
3. Configure: {{configuration_without_secrets}}
4. Run: \`{{run_command}}\`
5. Verify: \`{{verification_commands}}\`
6. Build artifact: \`{{build_command}}\`

## Quality gates

| Gate | Command/evidence | Blocks merge? | Owner |
| --- | --- | --- | --- |
| Types/contracts | {{command}} | {{yes_no}} | {{owner}} |
| Unit/integration | {{command}} | {{yes_no}} | {{owner}} |
| Security/dependencies | {{command_or_review}} | {{yes_no}} | {{owner}} |
| Production build | {{command}} | {{yes_no}} | {{owner}} |

## Operations and recovery

- Environments and deployment artifact: {{details}}
- Configuration and secret ownership: {{details}}
- Health, logs, metrics, traces, and alerts: {{details}}
- Migration ordering: {{details}}
- Rollback or forward-recovery procedure: {{details}}
- Incident owner and escalation: {{details}}

## Repository completion check

- [ ] A new contributor can run and verify the project from committed instructions.
- [ ] Ownership and dependency direction are visible from the tree and public interfaces.
- [ ] Generated, secret, build, and local state are excluded intentionally.
- [ ] CI executes the same meaningful commands developers run locally.
- [ ] Production-impacting changes have rollout, observability, and recovery evidence.`,
  ),
  template(
    "product",
    `# {{product_name}} Product Definition

Status: {{proposed|validated|planned|released}}
Owner: {{owner}}
Last validated: {{date}}

## User and problem

**Target user:** {{specific user or role}}

**Current behavior:** {{what they do today and where it fails}}

**Evidence:** {{research, support, analytics, or explicitly labeled hypothesis}}

**Problem statement:** {{user}} needs {{capability}} because {{evidence-backed reason}}. Today, {{current failure}} causes {{impact}}.

## Intended outcome

{{Observable user or business change. Avoid describing the implementation.}}

### Success measures

| Measure | Baseline | Target | Window | Data source | Guardrail |
| --- | --- | --- | --- | --- | --- |
| {{metric}} | {{value/unknown}} | {{target}} | {{period}} | {{source}} | {{must not worsen}} |

## Scope

### In scope

- {{minimum behavior required to produce the outcome}}

### Non-goals

- {{explicitly excluded behavior and why}}

### Assumptions to validate

| Assumption | Impact if false | Evidence needed | Validation method |
| --- | --- | --- | --- |
| {{assumption}} | {{impact}} | {{signal}} | {{test}}

## User journey and states

| Step/state | User intent | System behavior | Failure/recovery |
| --- | --- | --- | --- |
| {{step}} | {{intent}} | {{observable behavior}} | {{safe recovery}} |

Include loading, empty, success, validation, unauthorized, degraded, and failure states where applicable.

## Policy and constraints

- Actors and permissions: {{details}}
- Sensitive data, privacy, and retention: {{details}}
- Accessibility target: {{details}}
- Reliability/latency/cost constraints: {{details}}
- Legal/commercial constraints: {{details}}

## Acceptance criteria

- [ ] Given {{precondition}}, when {{action}}, then {{observable result}}.
- [ ] When {{dependency or input failure}}, the user sees {{safe behavior}} and can {{recover}}.
- [ ] {{resource}} is accessible only to {{authorized actor}}.

## Validation and rollout

- Smallest experiment or release slice: {{details}}
- Instrumentation and decision threshold: {{details}}
- Rollout stages and stop conditions: {{details}}
- Owner and review date: {{details}}`,
  ),
  template(
    "architecture",
    `# {{system_name}} Architecture

Status: {{current|proposed}}
Owners: {{owners}}
Last reviewed: {{date}}

## Requirements and constraints

- Product outcomes supported: {{links_or_summary}}
- Non-goals: {{details}}
- Expected load and SLOs: {{details}}
- Security, privacy, compliance, cost, and team constraints: {{details}}

## System context

| Actor/system | Trust level | Interaction | Data/authority exchanged |
| --- | --- | --- | --- |
| {{actor}} | {{trusted/untrusted/partial}} | {{operation}} | {{data_or_permission}} |

Describe synchronous requests, asynchronous work, and how partial failures reach the user/operator.

## Components and ownership

| Component | Owns | Public interface | Data owned | Depends on | Failure behavior |
| --- | --- | --- | --- | --- | --- |
| {{component}} | {{responsibility}} | {{contract}} | {{data}} | {{dependency}} | {{degraded/retry/recovery}} |

### Dependency rules

1. {{entry points depend inward on application/domain interfaces}}
2. {{infrastructure implements interfaces; domain does not import vendors}}
3. {{modules communicate through explicit contracts/events}}

## Critical flows

### {{flow_name}}

1. {{actor action}}
2. {{validation/auth/authorization}}
3. {{state transition and transaction boundary}}
4. {{external or asynchronous effect}}
5. {{response and observable signals}}

Failure, retry, idempotency, timeout, and recovery: {{details}}

## Data architecture

- Entities and ownership: {{details}}
- Invariants and transaction boundaries: {{details}}
- Tenant/sensitive-data isolation: {{details}}
- Index/access patterns: {{details}}
- Retention, deletion, backup, and restore: {{details}}
- Migration/backfill compatibility: {{details}}

## Contracts

- Public/internal APIs: {{links}}
- Authentication and resource authorization: {{details}}
- Events/jobs and delivery semantics: {{details}}
- Versioning, idempotency, pagination, and errors: {{details}}

## Security boundaries

| Boundary | Threat/abuse | Prevent | Detect | Recover |
| --- | --- | --- | --- | --- |
| {{boundary}} | {{scenario}} | {{control}} | {{signal}} | {{action}} |

## Deployment and operations

- Environments, artifacts, configuration, and secrets: {{details}}
- CI/CD, migrations, health/readiness, and rollout: {{details}}
- Logs, metrics, traces, alerts, dashboards, and owners: {{details}}
- Rollback or forward recovery and disaster recovery: {{details}}

## Capacity and evolution

| Constraint | Current limit/evidence | Trigger | Next action | Cost/consequence |
| --- | --- | --- | --- | --- |
| {{constraint}} | {{evidence}} | {{threshold}} | {{change}} | {{tradeoff}} |

## Decisions and risks

- Linked ADRs: {{links}}
- Accepted risks and owners: {{details}}
- Assumptions to validate: {{details}}
- Revisit triggers: {{details}}`,
  ),
  template(
    "feature",
    `# {{feature_name}}

Status: {{proposed|validated|planned|in_progress|released}}
Owner: {{owner}}
Product/architecture links: {{links}}

## Outcome and scope

- User need and evidence: {{details}}
- Intended observable outcome: {{details}}
- In scope: {{details}}
- Non-goals: {{details}}
- Assumptions/open decisions: {{details}}

## Behavior contract

### Actors and permissions

| Actor | May | Must not | Ownership rule |
| --- | --- | --- | --- |
| {{actor}} | {{actions}} | {{denied_actions}} | {{resource_scope}} |

### States and transitions

| Current state | Command/event | Preconditions | Next state | Side effects | Failure/retry |
| --- | --- | --- | --- | --- | --- |
| {{state}} | {{trigger}} | {{rules}} | {{next}} | {{effects}} | {{behavior}} |

### User-visible states

Cover success, loading, empty, validation, unauthorized, conflict, degraded dependency, and unexpected failure.

## Contract and data impact

- API/event schemas and stable errors: {{details_or_links}}
- Compatibility/versioning/idempotency: {{details}}
- Data model, constraints, indexes, and migration: {{details}}
- Sensitive data, retention, and audit: {{details}}

## Failure and operations

- External dependency timeout/retry/fallback: {{details}}
- Observability and user-safe errors: {{details}}
- Abuse/rate-limit/security controls: {{details}}
- Rollout, feature control, migration order, and recovery: {{details}}

## Acceptance criteria

- [ ] Given {{precondition}}, when {{action}}, then {{observable result}}.
- [ ] Unauthorized {{actor}} cannot {{action}} or infer {{resource}}.
- [ ] Duplicate/retried {{request_or_event}} produces {{idempotent result}}.
- [ ] When {{failure}}, the system {{degraded behavior}} and operator can {{recover}}.

## Verification matrix

| Risk/criterion | Test level | Case | Evidence |
| --- | --- | --- | --- |
| {{risk}} | {{unit/integration/contract/e2e/manual}} | {{case}} | {{command_or_result}} |

## Release and measurement

- Rollout stages and stop conditions: {{details}}
- Success/guardrail metrics: {{details}}
- Post-release checks and owner: {{details}}`,
  ),
  template(
    "adr",
    `# ADR-{{number}}: {{decision_title}}

Date: {{YYYY-MM-DD}}
Status: {{proposed|accepted|superseded|rejected}}
Owners: {{owners}}
Supersedes/superseded by: {{links_or_none}}

## Context

What decision is required now? Describe the current system, forces, evidence, constraints, and why the status quo is insufficient. Separate facts from assumptions.

## Decision drivers

1. {{requirement or constraint, ranked}}
2. {{security/reliability/cost/team consideration}}

## Considered options

### Option A — {{name}}

- How it works: {{details}}
- Benefits against drivers: {{details}}
- Costs and failure modes: {{details}}
- Migration/reversibility: {{details}}

### Option B — {{name}}

- How it works: {{details}}
- Benefits against drivers: {{details}}
- Costs and failure modes: {{details}}
- Migration/reversibility: {{details}}

## Decision

Choose {{option}} because {{reason tied to ranked drivers and evidence}}.

## Consequences

### Positive

- {{consequence}}

### Negative and accepted risks

- {{cost/risk, mitigation, owner}}

### Follow-up work

- {{required contract, migration, observability, security, or operational action}}

## Validation and rollout

- How the decision will be tested: {{details}}
- Rollout/migration sequence: {{details}}
- Rollback or forward recovery: {{details}}
- Signals and decision owner: {{details}}

## Revisit triggers

- {{measured threshold, new requirement, incident, cost, or capability change}}`,
  ),
  template(
    "api",
    `# {{api_or_operation_name}} Contract

Status/version: {{status}}
Owner: {{owner}}
Consumers: {{clients}}

## User operation

- Actor and intent: {{details}}
- Resource and ownership: {{details}}
- Preconditions/invariants: {{details}}
- State effect and side effects: {{details}}

## Operation

\`{{METHOD}} {{path}}\`

Authentication: {{scheme}}
Authorization: {{resource-level rule}}
Idempotency: {{key/scope/retention/result}}
Rate limit: {{identity/window/headers/error}}

## Request

### Path/query/header fields

| Field | Location | Type | Required | Validation/default | Meaning |
| --- | --- | --- | --- | --- | --- |
| {{field}} | {{path/query/header}} | {{type}} | {{yes/no}} | {{bounds}} | {{meaning}} |

### Body schema

\`\`\`json
{{request_example}}
\`\`\`

Unknown fields, normalization, size limits, and content type: {{details}}

## Success response

Status: \`{{status}}\`

\`\`\`json
{{response_example}}
\`\`\`

Headers/caching/pagination: {{details}}

## Error contract

| HTTP/status | Stable code | When | Safe client message | Retry/recovery |
| --- | --- | --- | --- | --- |
| {{status}} | {{code}} | {{condition}} | {{message}} | {{behavior}} |

Never expose secrets, stack traces, database details, or provider payloads.

## Concurrency and compatibility

- Optimistic concurrency/conflict behavior: {{details}}
- Duplicate/replay behavior: {{details}}
- Ordering and transaction boundary: {{details}}
- Versioning/deprecation/migration: {{details}}

## Security and operations

- Validation and abuse controls: {{details}}
- Sensitive data and logging/redaction: {{details}}
- Dependency timeout/fallback: {{details}}
- Metrics/traces/audit events: {{details}}

## Contract tests

- [ ] Valid request and exact response schema.
- [ ] Missing/malformed/boundary input for every constrained field.
- [ ] Unauthenticated, unauthorized, wrong-owner, and tenant-isolation cases.
- [ ] Duplicate, concurrent conflict, dependency failure, and rate-limit cases.
- [ ] Backward-compatibility case for existing consumers.`,
  ),
  template(
    "agent",
    `# Agent: {{agent_id}}

Description: {{One sentence stating the unique trigger and value.}}

## Responsibility

{{The single engineering outcome this agent owns.}}

## Strict boundaries

- Do not {{adjacent responsibility owned by another agent}}.
- Do not {{unsafe or low-evidence behavior}}.
- Do not {{scope expansion or authority violation}}.

## Engineering philosophy

- {{Decision principle specific to this specialty.}}
- {{Quality or evidence standard.}}
- {{Preferred trade-off under uncertainty.}}

## Preferred workflow

1. {{Discover authoritative context and restate the objective.}}
2. {{Analyze the specialty-specific system or evidence.}}
3. {{Evaluate alternatives or hypotheses.}}
4. {{Produce or implement the narrowest complete result.}}
5. {{Verify and report residual risk.}}

## Expected inputs

- {{Required task context}}
- {{Relevant repository/system evidence}}
- {{Constraints and permissions}}

## Expected outputs

- {{Primary artifact or implementation}}
- {{Evidence and verification}}
- {{Risks, decisions, or handoff}}

## Quality test

- Is the responsibility unique among installed agents?
- Would the boundaries prevent this agent from absorbing adjacent work?
- Are inputs discoverable and outputs objectively reviewable?
- Does the workflow require evidence before recommendation or mutation?`,
  ),
  template(
    "prompt",
    `# Prompt: {{prompt_id}}

Description: {{Specific task and outcome; include trigger words.}}
Argument hint: {{<required input> [optional focus]}}

## Task

{{Imperative outcome. State whether the prompt should analyze, plan, implement, or review.}}

Treat invocation arguments and current repository state as input. Discover local instructions and relevant sources of truth before making material assumptions.

## Method

1. {{Restate outcome, scope, evidence, and assumptions.}}
2. {{Inspect current behavior and affected boundaries.}}
3. {{Define contract, state, data, or risk before implementation detail.}}
4. {{Perform the task in the smallest complete sequence.}}
5. {{Verify important success and failure behavior.}}

## Deliverables

- {{Concrete artifact, decision, or implementation}}
- {{Tests/evidence/commands}}
- {{Risks, rollout, recovery, or unresolved decision}}

## Constraints

- Do not {{common failure mode specific to this prompt}}.
- Do not invent {{evidence, behavior, or authority}}.
- Do not claim completion without {{objective evidence}}.

## Quality test

- Does this encode a repeatable expert workflow rather than generic encouragement?
- Are deliverables objectively reviewable?
- Are consequential assumptions and unsafe shortcuts prohibited?
- Does the prompt end with evidence and residual risk?`,
  ),
];
