import type { AdapterRenderResult, IntegrationAdapter, IntegrationSpec } from "../types.js";
import {
  artifact,
  capability,
  capabilityProfile,
  generatedHeader,
  renderManagedInstructionBody,
  warning,
  validateRenderedArtifacts,
} from "./shared.js";

const capabilities = capability({ prompts: ["emulated", "Reusable prompts are collected in an always-read playbook."], hooks: ["unsupported", "Aider has no repository lifecycle hook surface."], skills: ["emulated", "Skill instructions are collected in an always-read playbook."], instructions: ["native", "CONVENTIONS.md is loaded through Aider's read configuration."], "slash-commands": ["unsupported", "Aider does not expose repository-defined slash commands."], agents: ["emulated", "Agent personas are collected in the playbook for manual adoption."], "automatic-context": ["native", "The read list loads configured project context."], "repository-onboarding": ["emulated", "Onboarding steps are included in CONVENTIONS.md."] });

export const aiderAdapter: IntegrationAdapter = {
  id: "aider",
  displayName: "Aider",
  runtime: {
    commands: ["aider"],
    projectMarkers: [".aider.conf.yml", "CONVENTIONS.md"],
    documentationUrl: "https://aider.chat/docs/usage/conventions.html",
  },
  capabilities,
  profile: capabilityProfile("aider.2026-07-15", capabilities),
  validate: (_root, artifacts) => validateRenderedArtifacts("aider", artifacts),
  render(spec: IntegrationSpec): AdapterRenderResult {
    const environment = "aider";
    const playbookSections: string[] = [
      generatedHeader(environment),
      "# Misbah's Build Like This playbook",
    ];
    for (const prompt of spec.prompts ?? []) {
      playbookSections.push(`## Prompt: ${prompt.id}\n\n${prompt.description}\n\n${prompt.prompt.trim()}`);
    }
    for (const skill of spec.skills ?? []) {
      playbookSections.push(`## Skill: ${skill.id}\n\n${skill.description}\n\n${skill.instructions.trim()}`);
    }
    for (const agent of spec.agents ?? []) {
      playbookSections.push(
        `## Persona: ${agent.id}\n\n${agent.description}\n\n${agent.instructions.trim()}`,
      );
    }

    const readPaths = [
      "CONVENTIONS.md",
      ...(playbookSections.length > 2 ? [".mstack/aider-playbook.md"] : []),
      ...(spec.context ?? []).map((source) => source.path),
    ];
    const artifacts = [
      artifact(
        environment,
        "instructions",
        "CONVENTIONS.md",
        renderManagedInstructionBody(spec, (path) => `\`${path}\``),
        "managed-block",
      ),
      artifact(
        environment,
        "automatic-context",
        ".aider.conf.yml",
        [
          `# Generated by mstack from Misbah's Build Like This workflow for ${environment}. Regenerate instead of editing.`,
          "read:",
          ...readPaths.map((path) => `  - ${JSON.stringify(path)}`),
        ].join("\n"),
        "manual",
      ),
      ...(playbookSections.length > 2
        ? [
            artifact(
              environment,
              "prompts",
              ".mstack/aider-playbook.md",
              playbookSections.join("\n\n"),
            ),
          ]
        : []),
    ];
    const diagnostics = [];
    if ((spec.hooks?.length ?? 0) > 0) {
      diagnostics.push(
        warning(environment, "hooks", `${spec.hooks?.length} hook(s) were skipped; Aider has no hook API.`),
      );
    }
    if ((spec.prompts?.length ?? 0) > 0) {
      diagnostics.push(
        warning(
          environment,
          "slash-commands",
          "Aider loads generated prompts as a playbook; users invoke them conversationally, not as slash commands.",
        ),
      );
    }
    return { artifacts, diagnostics };
  },
};
