import type {
  AdapterRenderResult,
  HookEvent,
  IntegrationAdapter,
  IntegrationSpec,
} from "../types.js";
import {
  artifact,
  capability,
  renderAgentMarkdown,
  renderInstructionBody,
  renderStandardSkillArtifacts,
  timeoutSeconds,
  yamlString,
} from "./shared.js";

const hookEvents: Record<HookEvent, string> = {
  "session-start": "SessionStart",
  "before-prompt": "UserPromptSubmit",
  "before-tool": "PreToolUse",
  "after-tool": "PostToolUse",
  "after-response": "Stop",
  "session-end": "SessionEnd",
};

export const claudeAdapter: IntegrationAdapter = {
  id: "claude-code",
  displayName: "Claude Code",
  runtime: {
    commands: ["claude"],
    projectMarkers: ["CLAUDE.md", ".claude"],
    documentationUrl: "https://code.claude.com/docs/en/claude-directory",
  },
  capabilities: capability({
    prompts: ["native", "Project skills provide reusable prompts."],
    hooks: ["native", "Lifecycle hooks are stored in .claude/settings.json."],
    skills: ["native", "Agent Skills are stored under .claude/skills."],
    instructions: ["native", "CLAUDE.md is loaded as project guidance."],
    "slash-commands": ["native", "User-invocable skills appear as slash commands."],
    agents: ["native", "Project subagents are stored under .claude/agents."],
    "automatic-context": ["native", "CLAUDE.md supports @path imports."],
    "repository-onboarding": ["native", "Project setup is loaded through CLAUDE.md."],
  }),
  render(spec: IntegrationSpec): AdapterRenderResult {
    const environment = "claude-code";
    const artifacts = [
      artifact(
        environment,
        "instructions",
        "CLAUDE.md",
        renderInstructionBody(spec, (path) => `@${path}`),
        "managed-block",
      ),
      ...renderStandardSkillArtifacts(environment, ".claude/skills", spec.skills ?? []),
      ...(spec.prompts ?? []).map((prompt) =>
        artifact(
          environment,
          "prompts",
          `.claude/skills/${prompt.id}/SKILL.md`,
          [
            "---",
            `name: ${yamlString(prompt.id)}`,
            `description: ${yamlString(prompt.description)}`,
            "user-invocable: true",
            "disable-model-invocation: true",
            ...(prompt.argumentHint === undefined
              ? []
              : [`argument-hint: ${yamlString(prompt.argumentHint)}`]),
            "---",
            "",
            "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
            "",
            prompt.prompt.trim(),
            "",
            "User arguments: $ARGUMENTS",
          ].join("\n"),
        ),
      ),
      ...(spec.agents ?? []).map((agent) =>
        artifact(
          environment,
          "agents",
          `.claude/agents/${agent.id}.md`,
          renderAgentMarkdown(agent),
        ),
      ),
    ];

    if ((spec.hooks?.length ?? 0) > 0) {
      const hooks: Record<string, unknown[]> = {};
      for (const hook of spec.hooks ?? []) {
        (hooks[hookEvents[hook.event]] ??= []).push({
          ...(hook.matcher === undefined ? {} : { matcher: hook.matcher }),
          hooks: [
            {
              type: "command",
              command: hook.command,
              ...(hook.timeoutMs === undefined ? {} : { timeout: timeoutSeconds(hook.timeoutMs) }),
            },
          ],
        });
      }
      artifacts.push(
        artifact(
          environment,
          "hooks",
          ".claude/settings.json",
          JSON.stringify({ hooks }, null, 2),
          "merge-json",
        ),
      );
    }
    return { artifacts, diagnostics: [] };
  },
};
