import type {
  AdapterRenderResult,
  HookEvent,
  IntegrationAdapter,
  IntegrationSpec,
} from "../types.js";
import {
  artifact,
  capability,
  capabilityProfile,
  renderManagedInstructionBody,
  renderPromptSkill,
  renderStandardSkillArtifacts,
  timeoutSeconds,
  tomlString,
  warning,
  validateRenderedArtifacts,
} from "./shared.js";

const hookEvents: Record<HookEvent, string> = {
  "session-start": "SessionStart",
  "before-prompt": "UserPromptSubmit",
  "before-tool": "PreToolUse",
  "after-tool": "PostToolUse",
  "after-response": "Stop",
  "session-end": "Stop",
};

const capabilities = capability({
  prompts: ["native", "Reusable prompts are represented as Agent Skills."], hooks: ["experimental", "Approved repository hooks are rendered inline in .codex/config.toml."], skills: ["native", "Open Agent Skills are stored under .agents/skills."], instructions: ["native", "AGENTS.md is loaded as repository guidance."], "slash-commands": ["emulated", "Repo-scoped skills replace deprecated personal custom prompts."], agents: ["native", "Project agents are standalone TOML files in .codex/agents."], "automatic-context": ["emulated", "AGENTS.md directs Codex to load relevant context paths."], "repository-onboarding": ["native", "Repository setup is loaded through AGENTS.md."], mcp: ["experimental", "Project MCP configuration is privileged shared TOML."], permissions: ["experimental", "Trust, sandbox, and approval settings are privileged shared TOML."],
});

export const codexAdapter: IntegrationAdapter = {
  id: "codex",
  displayName: "OpenAI Codex",
  runtime: {
    commands: ["codex"],
    projectMarkers: ["AGENTS.md", ".codex", ".agents/skills"],
    documentationUrl: "https://learn.chatgpt.com/docs/customization/overview",
  },
  capabilities,
  profile: capabilityProfile("codex.2026-07-15", capabilities),
  validate: (_root, artifacts) => validateRenderedArtifacts("codex", artifacts),
  render(spec: IntegrationSpec): AdapterRenderResult {
    const environment = "codex";
    const diagnostics = [];
    const artifacts = [
      artifact(
        environment,
        "instructions",
        "AGENTS.md",
        renderManagedInstructionBody(spec, (path) => `\`${path}\``),
        "managed-block",
      ),
      ...renderStandardSkillArtifacts(environment, ".agents/skills", spec.skills ?? []),
      ...(spec.prompts ?? []).map((prompt) =>
        artifact(
          environment,
          "prompts",
          `.agents/skills/${prompt.id}/SKILL.md`,
          renderPromptSkill(prompt),
        ),
      ),
      ...(spec.agents ?? []).map((agent) =>
        artifact(
          environment,
          "agents",
          `.codex/agents/${agent.id}.toml`,
          [
            `# Generated by mstack from Misbah's Build Like This workflow for ${environment}. Regenerate instead of editing.`,
            `name = ${tomlString(agent.id)}`,
            `description = ${tomlString(agent.description)}`,
            `developer_instructions = ${tomlString(agent.instructions)}`,
            ...(agent.model === undefined ? [] : [`model = ${tomlString(agent.model)}`]),
          ].join("\n"),
        ),
      ),
    ];

    if ((spec.prompts?.length ?? 0) > 0) {
      diagnostics.push(
        warning(
          environment,
          "slash-commands",
          "Codex custom prompts are deprecated and personal-only; generated prompts are invoked as $skills instead.",
        ),
      );
    }
    if ((spec.hooks?.length ?? 0) > 0 || (spec.mcpServers?.length ?? 0) > 0) {
      const config: string[] = [];
      for (const hook of spec.hooks ?? []) {
        const event = hookEvents[hook.event];
        config.push(
          `[[hooks.${event}]]`,
          ...(hook.matcher === undefined ? [] : [`matcher = ${tomlString(hook.matcher)}`]),
          "",
          `[[hooks.${event}.hooks]]`,
          `type = ${tomlString("command")}`,
          `command = ${tomlString(hook.command)}`,
          ...(hook.timeoutMs === undefined ? [] : [`timeout = ${timeoutSeconds(hook.timeoutMs)}`]),
          "",
        );
        if (hook.event === "session-end") {
          diagnostics.push(
            warning(
              environment,
              "hooks",
              `Hook '${hook.id}' uses Stop because Codex has no distinct repository SessionEnd event.`,
            ),
          );
        }
      }
      for (const server of spec.mcpServers ?? []) {
        config.push(
          `[mcp_servers.${tomlString(server.id)}]`,
          ...(server.url === undefined ? [] : [`url = ${tomlString(server.url)}`]),
          ...(server.command === undefined ? [] : [`command = ${tomlString(server.command)}`]),
          ...(server.args === undefined ? [] : [`args = ${JSON.stringify(server.args)}`]),
          "",
        );
      }
      artifacts.push(
        { ...artifact(environment, (spec.hooks?.length ?? 0) > 0 ? "hooks" : "mcp", ".codex/config.toml", config.join("\n"), "manual"), security: (spec.mcpServers?.length ?? 0) > 0 ? "network" : "executable", activation: "privileged", constraints: { "executable-change": (spec.hooks?.length ?? 0) > 0 } },
      );
    }
    return { artifacts, diagnostics };
  },
};
