import type {
  AdapterRenderResult,
  HookEvent,
  IntegrationAdapter,
  IntegrationSpec,
} from "../types.js";
import {
  artifact,
  capability,
  renderInstructionBody,
  renderPromptSkill,
  renderStandardSkillArtifacts,
  timeoutSeconds,
  tomlString,
  warning,
} from "./shared.js";

const hookEvents: Record<HookEvent, string> = {
  "session-start": "SessionStart",
  "before-prompt": "UserPromptSubmit",
  "before-tool": "PreToolUse",
  "after-tool": "PostToolUse",
  "after-response": "Stop",
  "session-end": "Stop",
};

export const codexAdapter: IntegrationAdapter = {
  id: "codex",
  displayName: "OpenAI Codex",
  runtime: {
    commands: ["codex"],
    projectMarkers: ["AGENTS.md", ".codex", ".agents/skills"],
    documentationUrl: "https://learn.chatgpt.com/docs/customization/overview",
  },
  capabilities: capability({
    prompts: ["native", "Reusable prompts are represented as Agent Skills."],
    hooks: ["native", "Lifecycle hooks are stored in .codex/hooks.json."],
    skills: ["native", "Open Agent Skills are stored under .agents/skills."],
    instructions: ["native", "AGENTS.md is loaded as repository guidance."],
    "slash-commands": ["emulated", "Repo-scoped skills replace deprecated personal custom prompts."],
    agents: ["native", "Project agents are standalone TOML files in .codex/agents."],
    "automatic-context": ["emulated", "AGENTS.md directs Codex to load relevant context paths."],
    "repository-onboarding": ["native", "Repository setup is loaded through AGENTS.md."],
  }),
  render(spec: IntegrationSpec): AdapterRenderResult {
    const environment = "codex";
    const diagnostics = [];
    const artifacts = [
      artifact(
        environment,
        "instructions",
        "AGENTS.md",
        renderInstructionBody(spec, (path) => `\`${path}\``),
        "managed-block",
      ),
      ...renderStandardSkillArtifacts(environment, ".agents/skills", spec.skills ?? []),
      ...(spec.prompts ?? []).map((prompt) =>
        artifact(
          environment,
          "prompts",
          `.agents/skills/${prompt.id}/SKILL.md`,
          renderPromptSkill(prompt),
        ),
      ),
      ...(spec.agents ?? []).map((agent) =>
        artifact(
          environment,
          "agents",
          `.codex/agents/${agent.id}.toml`,
          [
            `# Generated by mstack from Misbah's Build Like This workflow for ${environment}. Regenerate instead of editing.`,
            `name = ${tomlString(agent.id)}`,
            `description = ${tomlString(agent.description)}`,
            `developer_instructions = ${tomlString(agent.instructions)}`,
            ...(agent.model === undefined ? [] : [`model = ${tomlString(agent.model)}`]),
          ].join("\n"),
        ),
      ),
    ];

    if ((spec.prompts?.length ?? 0) > 0) {
      diagnostics.push(
        warning(
          environment,
          "slash-commands",
          "Codex custom prompts are deprecated and personal-only; generated prompts are invoked as $skills instead.",
        ),
      );
    }
    if ((spec.hooks?.length ?? 0) > 0) {
      const hooks: Record<string, unknown[]> = {};
      for (const hook of spec.hooks ?? []) {
        (hooks[hookEvents[hook.event]] ??= []).push({
          ...(hook.matcher === undefined ? {} : { matcher: hook.matcher }),
          hooks: [
            {
              type: "command",
              command: hook.command,
              ...(hook.timeoutMs === undefined ? {} : { timeout: timeoutSeconds(hook.timeoutMs) }),
            },
          ],
        });
        if (hook.event === "session-end") {
          diagnostics.push(
            warning(
              environment,
              "hooks",
              `Hook '${hook.id}' uses Stop because Codex has no distinct repository SessionEnd event.`,
            ),
          );
        }
      }
      artifacts.push(
        artifact(environment, "hooks", ".codex/hooks.json", JSON.stringify({ hooks }, null, 2), "merge-json"),
      );
    }
    return { artifacts, diagnostics };
  },
};
