import type { AdapterRenderResult, IntegrationAdapter, IntegrationSpec } from "../types.js";
import {
  artifact,
  capability,
  capabilityProfile,
  generatedHeader,
  renderInstructionBody,
  warning,
  yamlString,
  validateRenderedArtifacts,
} from "./shared.js";

const capabilities = capability({ prompts: ["native", "Invokable files under .continue/prompts provide reusable prompts."], hooks: ["unsupported", "Continue has no repository lifecycle hook surface."], skills: ["emulated", "Conditional rules provide on-demand instructions without bundled resources."], instructions: ["native", "Always-applied workspace rules provide project instructions."], "slash-commands": ["native", "Prompts with invokable: true appear as slash commands."], agents: ["native", "Project agents are stored under .continue/agents."], "automatic-context": ["emulated", "The workspace rule directs the agent to read relevant paths."], "repository-onboarding": ["native", "An always-applied workspace rule carries onboarding steps."] });

export const continueAdapter: IntegrationAdapter = {
  id: "continue",
  displayName: "Continue",
  runtime: {
    commands: ["cn", "continue"],
    projectMarkers: [".continue"],
    documentationUrl: "https://docs.continue.dev/customize/deep-dives/rules",
  },
  capabilities,
  profile: capabilityProfile("continue.2026-07-15", capabilities),
  validate: (_root, artifacts) => validateRenderedArtifacts("continue", artifacts),
  render(spec: IntegrationSpec): AdapterRenderResult {
    const environment = "continue";
    const diagnostics = [];
    const artifacts = [
      artifact(
        environment,
        "instructions",
        ".continue/rules/00-mstack.md",
        [
          "---",
          "name: Misbah's Build Like This project guidance",
          "description: Opinionated product-to-production instructions and repository onboarding",
          "alwaysApply: true",
          "---",
          "",
          generatedHeader(environment),
          renderInstructionBody(spec, (path) => `\`${path}\``),
        ].join("\n"),
      ),
      ...(spec.prompts ?? []).map((prompt) =>
        artifact(
          environment,
          "prompts",
          `.continue/prompts/${prompt.id}.md`,
          [
            "---",
            `name: ${yamlString(prompt.id)}`,
            `description: ${yamlString(prompt.description)}`,
            "invokable: true",
            "---",
            "",
            "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
            "",
            prompt.prompt.trim(),
          ].join("\n"),
        ),
      ),
      ...(spec.skills ?? []).map((skill) =>
        artifact(
          environment,
          "skills",
          `.continue/rules/skill-${skill.id}.md`,
          [
            "---",
            `name: ${yamlString(skill.id)}`,
            `description: ${yamlString(skill.description)}`,
            "alwaysApply: false",
            "---",
            "",
            "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
            "",
            skill.instructions.trim(),
          ].join("\n"),
        ),
      ),
      ...(spec.agents ?? []).map((agent) =>
        artifact(
          environment,
          "agents",
          `.continue/agents/${agent.id}.md`,
          [
            "---",
            `name: ${yamlString(agent.id)}`,
            `description: ${yamlString(agent.description)}`,
            "---",
            "",
            "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
            "",
            agent.instructions.trim(),
          ].join("\n"),
        ),
      ),
    ];

    if ((spec.hooks?.length ?? 0) > 0) {
      diagnostics.push(
        warning(
          environment,
          "hooks",
          `${spec.hooks?.length} hook(s) were skipped because Continue has no repository lifecycle hook surface.`,
        ),
      );
    }
    if ((spec.skills ?? []).some((skill) => (skill.resources?.length ?? 0) > 0)) {
      diagnostics.push(
        warning(
          environment,
          "skills",
          "Continue rule fallbacks include skill instructions but cannot bundle skill resources.",
        ),
      );
    }
    return { artifacts, diagnostics };
  },
};
