import type {
  AdapterRenderResult,
  HookEvent,
  IntegrationAdapter,
  IntegrationSpec,
} from "../types.js";
import {
  artifact,
  capability,
  capabilityProfile,
  renderAgentMarkdown,
  renderManagedInstructionBody,
  renderStandardSkillArtifacts,
  tomlString,
  validateRenderedArtifacts,
} from "./shared.js";

const hookEvents: Record<HookEvent, string> = {
  "session-start": "SessionStart",
  "before-prompt": "BeforeAgent",
  "before-tool": "BeforeTool",
  "after-tool": "AfterTool",
  "after-response": "AfterAgent",
  "session-end": "SessionEnd",
};

const capabilities = capability({ prompts: ["native", "Project commands are TOML prompt definitions."], hooks: ["native", "Lifecycle hooks are owned entries in .gemini/settings.json."], skills: ["native", "Open Agent Skills are stored under .agents/skills."], instructions: ["native", "GEMINI.md is loaded as project context."], "slash-commands": ["native", "Project TOML commands become slash commands."], agents: ["native", "Project subagents are stored under .gemini/agents."], "automatic-context": ["native", "GEMINI.md supports @path imports."], "repository-onboarding": ["native", "Repository setup is loaded through GEMINI.md."], mcp: ["native", "MCP servers are owned settings entries with explicit type and url."] });

export const geminiAdapter: IntegrationAdapter = {
  id: "gemini-cli",
  displayName: "Gemini CLI",
  runtime: {
    commands: ["gemini"],
    projectMarkers: [".gemini"],
    documentationUrl: "https://geminicli.com/docs/cli/gemini-md",
  },
  capabilities,
  profile: capabilityProfile("gemini-cli.2026-07-15", capabilities),
  validate: (_root, artifacts) => validateRenderedArtifacts("gemini-cli", artifacts),
  render(spec: IntegrationSpec): AdapterRenderResult {
    const environment = "gemini-cli";
    const artifacts = [
      artifact(
        environment,
        "instructions",
        "GEMINI.md",
        renderManagedInstructionBody(spec, (path) => `@${path}`),
        "managed-block",
      ),
      ...renderStandardSkillArtifacts(environment, ".agents/skills", spec.skills ?? []),
      ...(spec.prompts ?? []).map((prompt) =>
        artifact(
          environment,
          "prompts",
          `.gemini/commands/${prompt.id}.toml`,
          [
            `# Generated by mstack from Misbah's Build Like This workflow for ${environment}. Regenerate instead of editing.`,
            `description = ${tomlString(prompt.description)}`,
            `prompt = ${tomlString(`${prompt.prompt.trim()}\n\nUser arguments: {{args}}`)}`,
          ].join("\n"),
        ),
      ),
      ...(spec.agents ?? []).map((agent) =>
        artifact(
          environment,
          "agents",
          `.gemini/agents/${agent.id}.md`,
          renderAgentMarkdown(agent, ["kind: local"]),
        ),
      ),
    ];

    if ((spec.hooks?.length ?? 0) > 0 || (spec.mcpServers?.length ?? 0) > 0) {
      const hooks: Record<string, unknown[]> = {};
      for (const hook of spec.hooks ?? []) {
        (hooks[hookEvents[hook.event]] ??= []).push({
          name: hook.id,
          ...(hook.matcher === undefined ? {} : { matcher: hook.matcher }),
          hooks: [
            {
              type: "command",
              name: hook.id,
              command: hook.command,
              ...(hook.timeoutMs === undefined ? {} : { timeout: hook.timeoutMs }),
            },
          ],
        });
      }
      const mcpServers = Object.fromEntries((spec.mcpServers ?? []).map((server) => [server.id, server.type === "stdio" ? { type: "stdio", command: server.command, ...(server.args === undefined ? {} : { args: server.args }) } : { type: server.type, url: server.url }]));
      artifacts.push(
        artifact(
          environment,
          "hooks",
          ".gemini/settings.json",
          JSON.stringify({ ...(Object.keys(hooks).length === 0 ? {} : { hooks }), ...(Object.keys(mcpServers).length === 0 ? {} : { mcpServers }) }, null, 2),
          "merge-json",
        ),
      );
    }
    return { artifacts, diagnostics: [] };
  },
};
