import type {
  AdapterRenderResult,
  GeneratedArtifact,
  IntegrationAdapter,
  IntegrationDiagnostic,
  IntegrationSpec,
} from "../types.js";
import {
  artifact,
  capability,
  capabilityProfile,
  generatedHeader,
  renderAgentMarkdown,
  renderAgentsCompatibleArtifacts,
  renderPersonaSkillArtifacts,
  validateRenderedArtifacts,
  warning,
  yamlString,
} from "./shared.js";

interface MarkdownAdapterOptions {
  readonly id: string;
  readonly displayName: string;
  readonly commands: readonly string[];
  readonly projectMarkers: readonly string[];
  readonly documentationUrl: string;
  readonly platformVersion?: string;
  readonly skillBase: string;
  readonly promptBase?: string;
  readonly promptSuffix?: string;
  readonly agentBase?: string;
  readonly agentSuffix?: string;
  readonly agentFrontmatter?: readonly string[];
  readonly rulesBase?: string;
  readonly slashCommands: "native" | "emulated";
}

function createMarkdownAdapter(options: MarkdownAdapterOptions): IntegrationAdapter {
  const agentCapability = options.agentBase === undefined
    ? ["emulated", "Specialist definitions are installed as native persona skills because no stable auto-discovered project-agent format is verified."] as const
    : ["native", `Project specialist definitions are stored under ${options.agentBase}.`] as const;
  const ruleCapability = options.rulesBase === undefined
    ? ["unsupported", "No separate project-rule surface is rendered; AGENTS.md remains the verified instruction boundary."] as const
    : ["native", `Project rules are stored under ${options.rulesBase}.`] as const;
  const slashCapability = options.slashCommands === "native"
    ? ["native", options.promptBase === undefined ? "Prompt skills are directly invokable by name." : `Prompt commands are stored under ${options.promptBase}.`] as const
    : ["emulated", "Prompt packs are native skills but command-palette or slash invocation is runtime-dependent."] as const;
  const capabilities = capability({
    prompts: ["native", options.promptBase === undefined ? `Reusable prompts are native skills under ${options.skillBase}.` : `Reusable prompts are native project commands under ${options.promptBase}.`],
    hooks: ["unsupported", "No verified declarative project hook mapping is installed by this adapter."],
    skills: ["native", `Agent Skills are stored under ${options.skillBase}.`],
    instructions: ["native", "AGENTS.md is loaded as project guidance."],
    rules: ruleCapability,
    "slash-commands": slashCapability,
    agents: agentCapability,
    "automatic-context": ["native", "AGENTS.md supplies automatic project context and routes deeper reads."],
    "repository-onboarding": ["native", "Repository onboarding is loaded through AGENTS.md."],
    mcp: ["unsupported", "No common project MCP schema is rendered by this compatibility profile."],
    permissions: ["unsupported", "Permission and trust settings remain user-owned for this compatibility profile."],
  });

  return {
    id: options.id,
    displayName: options.displayName,
    runtime: {
      commands: options.commands,
      projectMarkers: options.projectMarkers,
      documentationUrl: options.documentationUrl,
    },
    capabilities,
    profile: capabilityProfile(
      `${options.id}.2026-07-18`,
      capabilities,
      "2026-07-18",
      options.platformVersion ?? "verified-current",
    ),
    validate: (_root, artifacts) => validateRenderedArtifacts(options.id, artifacts),
    render(spec: IntegrationSpec): AdapterRenderResult {
      const diagnostics: IntegrationDiagnostic[] = [];
      const artifacts: GeneratedArtifact[] = [
        ...renderAgentsCompatibleArtifacts(
          options.id,
          spec,
          options.skillBase,
          options.promptBase === undefined,
        ),
      ];

      if (options.promptBase !== undefined) {
        for (const prompt of spec.prompts ?? []) {
          artifacts.push(artifact(
            options.id,
            "prompts",
            `${options.promptBase}/${prompt.id}${options.promptSuffix ?? ".md"}`,
            [
              "---",
              `description: ${yamlString(prompt.description)}`,
              "---",
              "",
              "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
              "",
              prompt.prompt.trim(),
            ].join("\n"),
          ));
        }
      }

      if (options.agentBase === undefined) {
        artifacts.push(...renderPersonaSkillArtifacts(
          options.id,
          options.skillBase,
          spec.agents ?? [],
          spec.version ?? "0.0.0",
        ));
        if ((spec.agents?.length ?? 0) > 0) {
          diagnostics.push(warning(
            options.id,
            "agents",
            "Specialist agents were installed as persona skills; use native generic delegation when available or run the named passes sequentially.",
          ));
        }
      } else {
        for (const agent of spec.agents ?? []) {
          artifacts.push(artifact(
            options.id,
            "agents",
            `${options.agentBase}/${agent.id}${options.agentSuffix ?? ".md"}`,
            renderAgentMarkdown(agent, options.agentFrontmatter ?? []),
          ));
        }
      }

      if (options.rulesBase !== undefined) {
        for (const rule of spec.rules ?? []) {
          artifacts.push(artifact(
            options.id,
            "rules",
            `${options.rulesBase}/${rule.id}.md`,
            `${generatedHeader(options.id)}\n\n${rule.content.trim()}`,
          ));
        }
      }

      return { artifacts, diagnostics };
    },
  };
}

export const kimiCodeAdapter = createMarkdownAdapter({
  id: "kimi-code",
  displayName: "Kimi Code",
  commands: ["kimi"],
  projectMarkers: [],
  documentationUrl: "https://moonshotai.github.io/kimi-code/en/customization/skills",
  platformVersion: "1.17.0",
  skillBase: ".agents/skills",
  slashCommands: "native",
});

export const githubCopilotAdapter = createMarkdownAdapter({
  id: "github-copilot",
  displayName: "GitHub Copilot",
  commands: ["copilot"],
  projectMarkers: [".github/copilot-instructions.md", ".github/agents", ".github/prompts"],
  documentationUrl: "https://docs.github.com/en/copilot/reference/customization-cheat-sheet",
  skillBase: ".agents/skills",
  promptBase: ".github/prompts",
  promptSuffix: ".prompt.md",
  agentBase: ".github/agents",
  agentSuffix: ".agent.md",
  slashCommands: "native",
});

export const openCodeAdapter = createMarkdownAdapter({
  id: "opencode",
  displayName: "OpenCode",
  commands: ["opencode"],
  projectMarkers: [".opencode", "opencode.json", "opencode.jsonc"],
  documentationUrl: "https://opencode.ai/docs/rules/",
  platformVersion: "1.17.18",
  skillBase: ".agents/skills",
  promptBase: ".opencode/commands",
  agentBase: ".opencode/agents",
  agentFrontmatter: ["mode: subagent"],
  slashCommands: "native",
});

export const kiroAdapter = createMarkdownAdapter({
  id: "kiro",
  displayName: "Kiro",
  commands: ["kiro-cli"],
  projectMarkers: [".kiro"],
  documentationUrl: "https://kiro.dev/docs/skills/",
  skillBase: ".kiro/skills",
  rulesBase: ".kiro/steering/build-like-this",
  slashCommands: "emulated",
});

export const qwenCodeAdapter = createMarkdownAdapter({
  id: "qwen-code",
  displayName: "Qwen Code",
  commands: ["qwen"],
  projectMarkers: [".qwen"],
  documentationUrl: "https://qwenlm.github.io/qwen-code-docs/en/users/features/memory/",
  skillBase: ".qwen/skills",
  promptBase: ".qwen/commands",
  agentBase: ".qwen/agents",
  slashCommands: "native",
});

export const junieAdapter = createMarkdownAdapter({
  id: "junie",
  displayName: "Junie",
  commands: ["junie"],
  projectMarkers: [".junie"],
  documentationUrl: "https://junie.jetbrains.com/docs/guidelines-and-memory.html",
  skillBase: ".junie/skills",
  promptBase: ".junie/commands",
  agentBase: ".junie/agents",
  slashCommands: "native",
});

export const clineAdapter = createMarkdownAdapter({
  id: "cline",
  displayName: "Cline",
  commands: ["cline"],
  projectMarkers: [".cline", ".clinerules"],
  documentationUrl: "https://docs.cline.bot/customization/skills",
  skillBase: ".cline/skills",
  slashCommands: "emulated",
});

export const rooCodeAdapter = createMarkdownAdapter({
  id: "roo-code",
  displayName: "Roo Code",
  commands: [],
  projectMarkers: [".roo", ".roorules"],
  documentationUrl: "https://roocodeinc.github.io/Roo-Code/features/custom-instructions",
  skillBase: ".agents/skills",
  promptBase: ".roo/commands",
  slashCommands: "native",
});

export const portableAdapters: readonly IntegrationAdapter[] = [
  kimiCodeAdapter,
  githubCopilotAdapter,
  openCodeAdapter,
  kiroAdapter,
  qwenCodeAdapter,
  junieAdapter,
  clineAdapter,
  rooCodeAdapter,
];
