import type {
  AgentDefinition,
  CapabilityMap,
  GeneratedArtifact,
  IntegrationDiagnostic,
  IntegrationFeature,
  IntegrationSpec,
  PromptDefinition,
  SkillDefinition,
} from "../types.js";

export function capability(
  values: Record<IntegrationFeature, readonly ["native" | "emulated" | "unsupported", string]>,
): CapabilityMap {
  return Object.fromEntries(
    Object.entries(values).map(([feature, [level, detail]]) => [feature, { level, detail }]),
  ) as unknown as CapabilityMap;
}

export function artifact(
  environment: string,
  feature: IntegrationFeature,
  path: string,
  content: string,
  mergeStrategy: GeneratedArtifact["mergeStrategy"] = "replace",
): GeneratedArtifact {
  return { environment, feature, path, content: ensureNewline(content), mergeStrategy };
}

export function warning(
  environment: string,
  feature: IntegrationFeature,
  message: string,
): IntegrationDiagnostic {
  return { environment, feature, level: "warning", message };
}

export function renderInstructionBody(
  spec: IntegrationSpec,
  contextRenderer: (path: string) => string,
): string {
  const sections: string[] = [`# ${spec.project.name}`];
  if (spec.project.description !== undefined) sections.push(spec.project.description.trim());
  if (spec.instructions !== undefined) {
    sections.push(`## Project instructions\n\n${spec.instructions.content.trim()}`);
  }
  if ((spec.context?.length ?? 0) > 0) {
    sections.push(
      `## Required context\n\n${spec.context
        ?.map((source) => {
          const suffix = source.description === undefined ? "" : ` — ${source.description}`;
          const requirement = source.required === false ? "Optional" : "Load before relevant work";
          return `- ${requirement}: ${contextRenderer(source.path)}${suffix}`;
        })
        .join("\n")}`,
    );
  }
  if (spec.onboarding !== undefined) {
    const lines: string[] = [];
    if (spec.onboarding.summary !== undefined) lines.push(spec.onboarding.summary.trim());
    if ((spec.onboarding.setupCommands?.length ?? 0) > 0) {
      lines.push(
        `### Setup\n\n${spec.onboarding.setupCommands?.map((command) => `- \`${command}\``).join("\n")}`,
      );
    }
    if ((spec.onboarding.verificationCommands?.length ?? 0) > 0) {
      lines.push(
        `### Verify\n\n${spec.onboarding.verificationCommands
          ?.map((command) => `- \`${command}\``)
          .join("\n")}`,
      );
    }
    sections.push(`## Repository onboarding\n\n${lines.join("\n\n")}`);
  }
  return sections.join("\n\n");
}

export function renderStandardSkill(skill: SkillDefinition): string {
  return [
    "---",
    `name: ${yamlString(skill.id)}`,
    `description: ${yamlString(oneLine(skill.description))}`,
    "---",
    "",
    "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
    "",
    skill.instructions.trim(),
  ].join("\n");
}

export function renderStandardSkillArtifacts(
  environment: string,
  base: string,
  skills: readonly SkillDefinition[],
): GeneratedArtifact[] {
  return skills.flatMap((skill) => {
    const root = `${base}/${skill.id}`;
    return [
      artifact(environment, "skills", `${root}/SKILL.md`, renderStandardSkill(skill)),
      ...(skill.resources ?? []).map((resource) =>
        artifact(environment, "skills", `${root}/${resource.path}`, resource.content),
      ),
    ];
  });
}

export function renderPromptSkill(prompt: PromptDefinition): string {
  return [
    "---",
    `name: ${yamlString(prompt.id)}`,
    `description: ${yamlString(prompt.description)}`,
    "---",
    "",
    "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
    "",
    prompt.prompt.trim(),
    "",
    "Apply any arguments supplied by the user as task-specific input.",
  ].join("\n");
}

export function renderAgentMarkdown(agent: AgentDefinition, extra: readonly string[] = []): string {
  return [
    "---",
    `name: ${yamlString(agent.id)}`,
    `description: ${yamlString(oneLine(agent.description))}`,
    ...(agent.model === undefined ? [] : [`model: ${yamlString(agent.model)}`]),
    ...(agent.tools === undefined || agent.tools.length === 0
      ? []
      : ["tools:", ...agent.tools.map((tool) => `  - ${yamlString(tool)}`)]),
    ...extra,
    "---",
    "",
    "<!-- Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing. -->",
    "",
    agent.instructions.trim(),
  ].join("\n");
}

export function generatedHeader(environment: string): string {
  return `<!-- Generated by mstack from Misbah's Build Like This workflow for ${environment}. Regenerate instead of editing. -->`;
}

export function yamlString(value: string): string {
  return JSON.stringify(oneLine(value));
}

export function tomlString(value: string): string {
  return JSON.stringify(value);
}

export function timeoutSeconds(timeoutMs: number): number {
  return Math.max(1, Math.ceil(timeoutMs / 1_000));
}

export function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function ensureNewline(content: string): string {
  return `${content.trimEnd()}\n`;
}
