import { access, chmod, mkdir, readFile, realpath, rename, rm, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import type {
  AppliedArtifact,
  ApplyResult,
  GeneratedArtifact,
  IntegrationPlan,
} from "../types.js";
import { assertSafeRelativePath } from "./validation.js";

export interface ApplyOptions {
  readonly dryRun?: boolean;
  readonly force?: boolean;
}

export async function applyIntegrationPlan(
  root: string,
  plan: IntegrationPlan,
  options: ApplyOptions = {},
): Promise<ApplyResult> {
  const repositoryRoot = await realpath(resolve(root));
  const files: AppliedArtifact[] = [];

  for (const artifact of plan.artifacts) {
    assertSafeRelativePath(artifact.path, "artifact path");
    const absolutePath = resolve(repositoryRoot, artifact.path);
    if (!isInside(repositoryRoot, absolutePath)) {
      throw new Error(`Artifact escapes repository root: ${artifact.path}`);
    }
    await assertParentInside(repositoryRoot, absolutePath, artifact.path);

    const current = await readOptional(absolutePath);
    const next = mergeArtifact(current, artifact);
    if (current === next) {
      files.push({ path: artifact.path, status: "unchanged" });
      continue;
    }

    const managed = current === undefined || isManaged(current, artifact);
    if (!managed && artifact.mergeStrategy === "replace" && options.force !== true) {
      files.push({
        path: artifact.path,
        status: "conflict",
        message: "Existing unmanaged file was preserved. Pass force: true to replace it.",
      });
      continue;
    }

    if (options.dryRun !== true) {
      await mkdir(dirname(absolutePath), { recursive: true });
      let backupPath: string | undefined;
      if (!managed && artifact.mergeStrategy === "replace" && options.force === true && current !== undefined) {
        backupPath = `${absolutePath}.mstack-backup-${new Date().toISOString().replace(/[:.]/g, "-")}`;
        await writeFile(backupPath, current, "utf8");
      }
      await atomicWrite(absolutePath, next);
      if (artifact.executable === true) await chmod(absolutePath, 0o755);
      files.push({
        path: artifact.path,
        status: current === undefined ? "created" : "updated",
        ...(backupPath === undefined ? {} : { message: `Backup created at ${relative(repositoryRoot, backupPath)}` }),
      });
      continue;
    }
    files.push({ path: artifact.path, status: current === undefined ? "created" : "updated" });
  }

  return { files, diagnostics: plan.diagnostics };
}

function mergeArtifact(current: string | undefined, artifact: GeneratedArtifact): string {
  switch (artifact.mergeStrategy) {
    case "replace":
      return artifact.content;
    case "managed-block":
      return mergeManagedBlock(current, artifact.environment, artifact.content);
    case "merge-json": {
      const existing = current === undefined ? {} : parseObject(current, artifact.path);
      const generated = parseObject(artifact.content, artifact.path);
      return `${JSON.stringify(deepMerge(existing, generated), null, 2)}\n`;
    }
  }
}

function mergeManagedBlock(current: string | undefined, id: string, body: string): string {
  const start = `<!-- mstack:${id}:start -->`;
  const end = `<!-- mstack:${id}:end -->`;
  const block = `${start}\n${body.trim()}\n${end}`;
  if (current === undefined || current.trim().length === 0) return `${block}\n`;

  const startIndex = current.indexOf(start);
  const endIndex = current.indexOf(end);
  if (startIndex >= 0 && endIndex >= startIndex) {
    return `${current.slice(0, startIndex)}${block}${current.slice(endIndex + end.length)}`;
  }
  return `${current.trimEnd()}\n\n${block}\n`;
}

function isManaged(current: string, artifact: GeneratedArtifact): boolean {
  return (
    current.includes(`Generated by mstack from Misbah's Build Like This workflow for ${artifact.environment}`) ||
    current.includes("Generated by mstack from Misbah's Build Like This workflow. Regenerate instead of editing.") ||
    current.includes(`Generated by mstack for ${artifact.environment}`) ||
    current.includes("Generated by mstack. Regenerate instead of editing.")
  );
}

function parseObject(content: string, path: string): Record<string, unknown> {
  let value: unknown;
  try {
    value = JSON.parse(content);
  } catch (error) {
    throw new Error(`Cannot merge invalid JSON at ${path}`, { cause: error });
  }
  if (value === null || Array.isArray(value) || typeof value !== "object") {
    throw new Error(`Expected a JSON object at ${path}`);
  }
  return value as Record<string, unknown>;
}

function deepMerge(
  left: Record<string, unknown>,
  right: Record<string, unknown>,
): Record<string, unknown> {
  const result: Record<string, unknown> = { ...left };
  for (const [key, value] of Object.entries(right)) {
    const previous = result[key];
    if (isObject(previous) && isObject(value)) {
      result[key] = deepMerge(previous, value);
    } else if (Array.isArray(previous) && Array.isArray(value)) {
      const seen = new Set(previous.map(stableValue));
      result[key] = [...previous, ...value.filter((item) => !seen.has(stableValue(item)))];
    } else {
      result[key] = value;
    }
  }
  return result;
}

function isObject(value: unknown): value is Record<string, unknown> {
  return value !== null && !Array.isArray(value) && typeof value === "object";
}

function stableValue(value: unknown): string {
  return JSON.stringify(value, Object.keys(isObject(value) ? value : {}).sort());
}

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

async function assertParentInside(root: string, path: string, artifactPath: string): Promise<void> {
  let candidate = dirname(path);
  while (true) {
    try {
      const resolvedParent = await realpath(candidate);
      if (!isInside(root, resolvedParent)) {
        throw new Error(`Artifact parent resolves outside repository root: ${artifactPath}`);
      }
      return;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
      const parent = dirname(candidate);
      if (parent === candidate) throw error;
      candidate = parent;
    }
  }
}

function isInside(root: string, path: string): boolean {
  const repositoryRelative = relative(root, path);
  return (
    repositoryRelative === "" ||
    (repositoryRelative !== ".." &&
      !repositoryRelative.startsWith("../") &&
      !repositoryRelative.startsWith("..\\") &&
      !isAbsolute(repositoryRelative))
  );
}

async function atomicWrite(path: string, content: string): Promise<void> {
  const suffix = `${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const temporary = join(dirname(path), `.${suffix}.tmp`);
  const backup = join(dirname(path), `.${suffix}.bak`);
  let existed = true;
  try { await access(path); } catch { existed = false; }
  try {
    await writeFile(temporary, content, "utf8");
    if (existed) await rename(path, backup);
    await rename(temporary, path);
    if (existed) await rm(backup, { force: true });
  } catch (error) {
    let backupExists = true;
    try { await access(backup); } catch { backupExists = false; }
    let destinationExists = true;
    try { await access(path); } catch { destinationExists = false; }
    if (existed && backupExists && !destinationExists) await rename(backup, path);
    throw error;
  } finally {
    await rm(temporary, { force: true }).catch(() => undefined);
    await rm(backup, { force: true }).catch(() => undefined);
  }
}
